### ISSUE TITLE
WRITE/READ locking attempt on 'some table',  Possible deadlock avoided

### ISSUE THREAD

**Issue by peaksnail** [ClickHouse/ClickHouse#14436]
hi team

I exectute the sql and then I can't operate the table bill.(It's not clear whether this operation cause this)
```
alter table bill add column field UInt8 default 0
```

ch version 20.5.4.40

log detail

>2020.09.03 15:07:01.551829 [ 15388 ] {d0fe040e-5087-45de-ae2a-6b66cb1f0b28} <Error> executeQuery: Code: 473, e.displayText() = DB::Exception: WRITE locking attempt on "abacus.bill" has timed out! (120000ms) Possible deadlock avoided. Client should retry. (version 20.5.4.40) (from 127.0.0.1:34818) (in query: alter table bill add column sceneType UInt8 default 0), Stack trace (when copying this message, always include the lines below):
```
0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xcc3083c in /usr/bin/click
house
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x5a54619 in /usr/bin/clickho
use
2. ? @ 0x56a5475 in /usr/bin/clickhouse
3. DB::IStorage::lockStructureExclusively(DB::TableStructureWriteLockHolder&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<ch
ar> > const&, DB::SettingTimespan<(DB::SettingTimespanIO)1> const&) @ 0x9ffb07d in /usr/bin/clickhouse
4. DB::StorageMergeTree::alter(DB::AlterCommands const&, DB::Context const&, DB::TableStructureWriteLockHolder&) @ 0xa07a87d in /usr/bin/clickhouse
5. DB::InterpreterAlterQuery::execute() @ 0xa761ab8 in /usr/bin/clickhouse
6. ? @ 0x9f0152e in /usr/bin/clickhouse
7. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage
::Enum, bool) @ 0x9f04b87 in /usr/bin/clickhouse
8. DB::TCPHandler::runImpl() @ 0xa312696 in /usr/bin/clickhouse
9. DB::TCPHandler::run() @ 0xa313289 in /usr/bin/clickhouse
10. Poco::Net::TCPServerConnection::start() @ 0xcb6f517 in /usr/bin/clickhouse
11. Poco::Net::TCPServerDispatcher::run() @ 0xcb6f90b in /usr/bin/clickhouse
12. Poco::PooledThread::run() @ 0xcca652e in /usr/bin/clickhouse
13. Poco::ThreadImpl::runnableEntry(void*) @ 0xcca3229 in /usr/bin/clickhouse
14. start_thread @ 0x7e65 in /usr/lib64/libpthread-2.17.so
15. __clone @ 0xfe88d in /usr/lib64/libc-2.17.so

```

>2020.09.03 15:07:03.213738 [ 29841 ] {} <Error> DynamicQueryHandler: Code: 473, e.displayText() = DB::Exception: READ locking attempt on "abacus.bill" has timed out! (120000ms) Possible deadlock avoided. Client should retry., Stack trace (when copying this message, always include the lines below):

```
0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xcc3083c in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x5a54619 in /usr/bin/clickhouse
2. ? @ 0x56a5475 in /usr/bin/clickhouse
3. DB::IStorage::lockStructureForShare(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::SettingTimespan<(DB::SettingTimespanIO)1> const&) @ 0x9ffaf3f in /usr/bin/clickhouse
4. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x9e15129 in /usr/bin/clickhouse
5. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x9e16d46 in /usr/bin/clickhouse
6. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x9e32c26 in /usr/bin/clickhouse
7. DB::InterpreterSelectWithUnionQuery::getSampleBlock(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&) @ 0x9e339dd in /usr/bin/clickhouse
8. ? @ 0x9f0a0b6 in /usr/bin/clickhouse
9. DB::getDatabaseAndTablesWithColumns(std::__1::vector<DB::ASTTableExpression const*, std::__1::allocator<DB::ASTTableExpression const*> > const&, DB::Context const&) @ 0x9f0b3a0 in /usr/bin/clickhouse
10. DB::JoinedTables::resolveTables() @ 0x9e6b673 in /usr/bin/clickhouse
11. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x9e15d96 in /usr/bin/clickhouse
12. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x9e16d46 in /usr/bin/clickhouse
13. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x9e32c26 in /usr/bin/clickhouse
14. DB::InterpreterSelectWithUnionQuery::getSampleBlock(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&) @ 0x9e339dd in /usr/bin/clickhouse
15. ? @ 0x9f0a0b6 in /usr/bin/clickhouse
16. DB::getDatabaseAndTablesWithColumns(std::__1::vector<DB::ASTTableExpression const*, std::__1::allocator<DB::ASTTableExpression const*> > const&, DB::Context const&) @ 0x9f0b3a0 in /usr/bin/clickhouse
17. DB::JoinedTables::resolveTables() @ 0x9e6b673 in /usr/bin/clickhouse
18. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x9e15d96 in /usr/bin/clickhouse
19. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x9e16d46 in /usr/bin/clickhouse
20. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x9e32c26 in /usr/bin/clickhouse
21. DB::InterpreterSelectWithUnionQuery::getSampleBlock(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&) @ 0x9e339dd in /usr/bin/clickhouse
22. ? @ 0x9f0a0b6 in /usr/bin/clickhouse
23. DB::getDatabaseAndTablesWithColumns(std::__1::vector<DB::ASTTableExpression const*, std::__1::allocator<DB::ASTTableExpression const*> > const&, DB::Context const&) @ 0x9f0b3a0 in /usr/bin/clickhouse
24. DB::JoinedTables::resolveTables() @ 0x9e6b673 in /usr/bin/clickhouse
25. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x9e15d96 in /usr/bin/clickhouse
26. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x9e16d46 in /usr/bin/clickhouse
27. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x9e32c26 in /usr/bin/clickhouse
28. DB::InterpreterSelectWithUnionQuery::getSampleBlock(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&) @ 0x9e339dd in /usr/bin/clickhouse
29. ? @ 0x9f0a0b6 in /usr/bin/clickhouse
30. DB::getDatabaseAndTablesWithColumns(std::__1::vector<DB::ASTTableExpression const*, std::__1::allocator<DB::ASTTableExpression const*> > const&, DB::Context const&) @ 0x9f0b3a0 in /usr/bin/clickhouse
31. DB::JoinedTables::resolveTables() @ 0x9e6b673 in /usr/bin/clickhouse
 (version 20.5.4.40)
```

**Comment by peaksnail** [comment]
https://github.com/ClickHouse/ClickHouse/issues/13873

**Comment by den-crane** [comment]
It's kinda expected behavior and could happen sometimes. Alter could not start for 120000ms because it blocked by other queries. 

Try to increase user session parameter

lock_acquire_timeout - 120 (  How long locking request should wait before failing)

**Comment by peaksnail** [comment]
hi

what operation will cause this?  I have do nothing on the table ,and it's locked.

**Comment by den-crane** [comment]
Can you provide a CH logfile to see what queries were running at the same time as the error happen?

**Comment by peaksnail** [comment]
I found the query was running and only cost 689ms
```
 select * from (
    select * from
      (
        
    select 
      *,
      if(enableStock=1,openingStock,nan) as openingStock, 
      if(enableStock=1,openingCost,nan) as openingCost, 
      if(enableStock=1,endingStock,nan) as endingStock, 
      if(enableStock=1,endingCost,nan) as endingCost, 
      if(enableStock=1,endingCostUnitPrice,nan) as endingCostUnitPrice, 
      if(enableStock=1,openingDepositStock,nan) as openingDepositStock, 
      if(enableStock=1,endingDepositStock,nan) as endingDepositStock
    from (
      select
        warehouseId,
        goodsId,
        anyLast(goodsCategoryId) as goodsCategoryIdAlias,
        argMin(openingStock, eventDate) as openingStock,
        argMin(openingCost, eventDate) as openingCost,
        argMax(endingStock, eventDate) as endingStock,
        argMax(endingCost, eventDate) as endingCost,
        argMax(endingCostUnitPrice, eventDate) as endingCostUnitPrice,
        argMin(openingDepositStock, eventDate) as openingDepositStock,
        argMax(endingDepositStock, eventDate) as endingDepositStock,
        sum(purchaseCount) as allPurchaseCount,
        sum(purchaseCount * purchasePrice)/if(allPurchaseCount=0,1,allPurchaseCount) as purchasePrice,
        sum(salesCount) as salesCount,
        sum(salesCost) as salesCost,
        sum(salesOutboundCost) as salesOutboundCost,
        sum(giftCount) as giftCount,
        sum(giftCost) as giftCost,
        sum(inboundTransferCount) as inboundTransferCount,
        sum(inboundTransferCost) as inboundTransferCost,
        sum(outboundTransferCount) as outboundTransferCount,
        sum(outboundTransferCost) as outboundTransferCost,
        sum(returnCount) as allReturnCount,
        sum(returnCount * returnPrice)/if(allReturnCount=0,1,allReturnCount) as returnPrice,
        sum(profitCount) as profitCount,
        sum(profitFee) as profitFee,
        sum(lossCount) as lossCount,
        sum(lossFee) as lossFee,
        sum(depositCount) as depositCount,
        sum(depositFee) as depositFee,
        sum(takeCount) as takeCount,
        sum(takeFee) as takeFee,
        sum(confiscationInCount) as confiscationInCount,
        sum(confiscationInFee) as confiscationInFee,
        sum(confiscationOutCount) as confiscationOutCount,
        sum(confiscationOutFee) as confiscationOutFee,
        sum(requisitionCount) as requisitionCount,
        sum(requisitionFee) as requisitionFee,
        sum(scrapCount) as scrapCount,
        sum(scrapFee) as scrapFee
      from goods_invoicing where storeId='e1b2bb82-c760-48a0-88a0-a9295caec595'
       and eventDate>='2020-09-14' and eventDate<'2020-09-15'
      
      
      group by warehouseId,goodsId
    ) any left join (
      select
        goodsId,
        sortNo as goodsSortNo,
        name,
        unit,
        pack,
        enableStock
      from goods final where storeId='e1b2bb82-c760-48a0-88a0-a9295caec595' 
    ) using goodsId where 1=1 
  
      ) any left join (
        select name as warehouse, warehouseId from warehouse final where storeId='e1b2bb82-c760-48a0-88a0-a9295caec595'
    ) using warehouseId
  ) any left join (
    select 
      sortNo as goodsCategorySortNo,
      name as goodsCategory,
      goodsCategoryId as goodsCategoryIdAlias 
    from goods_category final where storeId='e1b2bb82-c760-48a0-88a0-a9295caec595'
  ) using goodsCategoryIdAlias
  
    order
    by goodsCategorySortNo,goodsCategory,goodsSortNo desc,name limit 0,50 FORMAT JSON
```

table goods_invoicing
```
DESCRIBE TABLE goods_invoicing

┌─name──────────────────┬─type─────┬─default_type─┬─default_expression────────────┬─comment─┬─codec_expression─┬─ttl_expression─┐
│ storeId               │ String   │              │                               │         │                  │                │
│ goodsId               │ String   │              │                               │         │                  │                │
│ goodsCategoryId       │ String   │              │                               │         │                  │                │
│ warehouseId           │ String   │              │                               │         │                  │                │
│ openingStock          │ Float32  │ DEFAULT      │ CAST(0, 'Float32')            │         │                  │                │
│ openingCost           │ Float32  │ DEFAULT      │ CAST(0, 'Float32')            │         │                  │                │
│ endingStock           │ Float32  │ DEFAULT      │ CAST(0, 'Float32')            │         │                  │                │
│ endingCost            │ Float32  │ DEFAULT      │ CAST(0, 'Float32')            │         │                  │                │
│ endingCostUnitPrice   │ Float32  │ DEFAULT      │ CAST(0, 'Float32')            │         │                  │                │
│ openingDepositStock   │ Float32  │ DEFAULT      │ CAST(0, 'Float32')            │         │                  │                │
│ endingDepositStock    │ Float32  │ DEFAULT      │ CAST(0, 'Float32')            │         │                  │                │
│ purchaseCount         │ Float32  │ DEFAULT      │ CAST(0, 'Float32')            │         │                  │                │
│ purchasePrice         │ Float32  │ DEFAULT      │ CAST(0, 'Float32')            │         │                  │                │
│ salesCount            │ Float32  │ DEFAULT      │ CAST(0, 'Float32')            │         │                  │                │
│ salesCost             │ Float32  │ DEFAULT      │ CAST(0, 'Float32')            │         │                  │                │
│ salesOutboundCost     │ Float32  │ DEFAULT      │ CAST(0, 'Float32')            │         │                  │                │
│ giftCount             │ Float32  │ DEFAULT      │ CAST(0, 'Float32')            │         │                  │                │
│ giftCost              │ Float32  │ DEFAULT      │ CAST(0, 'Float32')            │         │                  │                │
│ outboundTransferCount │ Float32  │ DEFAULT      │ CAST(0, 'Float32')            │         │                  │                │
│ outboundTransferCost  │ Float32  │ DEFAULT      │ CAST(0, 'Float32')            │         │                  │                │
│ inboundTransferCount  │ Float32  │ DEFAULT      │ CAST(0, 'Float32')            │         │                  │                │
│ inboundTransferCost   │ Float32  │ DEFAULT      │ CAST(0, 'Float32')            │         │                  │                │
│ returnCount           │ Float32  │ DEFAULT      │ CAST(0, 'Float32')            │         │                  │                │
│ returnPrice           │ Float32  │ DEFAULT      │ CAST(0, 'Float32')            │         │                  │                │
│ profitCount           │ Float32  │ DEFAULT      │ CAST(0, 'Float32')            │         │                  │                │
│ profitFee             │ Float32  │ DEFAULT      │ CAST(0, 'Float32')            │         │                  │                │
│ lossCount             │ Float32  │ DEFAULT      │ CAST(0, 'Float32')            │         │                  │                │
│ lossFee               │ Float32  │ DEFAULT      │ CAST(0, 'Float32')            │         │                  │                │
│ depositCount          │ Float32  │ DEFAULT      │ CAST(0, 'Float32')            │         │                  │                │
│ depositFee            │ Float32  │ DEFAULT      │ CAST(0, 'Float32')            │         │                  │                │
│ takeCount             │ Float32  │ DEFAULT      │ CAST(0, 'Float32')            │         │                  │                │
│ takeFee               │ Float32  │ DEFAULT      │ CAST(0, 'Float32')            │         │                  │                │
│ confiscationInCount   │ Float32  │ DEFAULT      │ CAST(0, 'Float32')            │         │                  │                │
│ confiscationInFee     │ Float32  │ DEFAULT      │ CAST(0, 'Float32')            │         │                  │                │
│ createDate            │ Int64    │              │                               │         │                  │                │
│ eventDate             │ Date     │ DEFAULT      │ toDate(createDate / 1000)     │         │                  │                │
│ eventDateTime         │ DateTime │ DEFAULT      │ toDateTime(createDate / 1000) │         │                  │                │
│ requisitionCount      │ Float32  │ DEFAULT      │ CAST(0, 'Float32')            │         │                  │                │
│ requisitionFee        │ Float32  │ DEFAULT      │ CAST(0, 'Float32')            │         │                  │                │
│ scrapCount            │ Float32  │ DEFAULT      │ CAST(0, 'Float32')            │         │                  │                │
│ scrapFee              │ Float32  │ DEFAULT      │ CAST(0, 'Float32')            │         │                  │                │
│ confiscationOutCount  │ Float32  │ DEFAULT      │ 0                             │         │                  │                │
│ confiscationOutFee    │ Float32  │ DEFAULT      │ 0                             │         │                  │                │
│ confiscationCount     │ Float32  │ DEFAULT      │ confiscationInCount           │         │                  │                │
│ confiscationFee       │ Float32  │ DEFAULT      │ confiscationInCount           │         │                  │                │
└───────────────────────┴──────────┴──────────────┴───────────────────────────────┴─────────┴──────────────────┴────────────────┘


```

But it block me about 10 minutes

**Comment by den-crane** [comment]
but did you alter `bill` or `goods_invoicing` ? Is this table related? Materialized view or View ?

**Comment by zhang2014** [comment]
We also encountered the same problem, which was solved by  upgrading to 20.6.4.44(we have not encountered this problem so far). for more information: https://github.com/ClickHouse/ClickHouse/pull/11745 (Not sure why is tag is inconsistent with the actual release version)

**Comment by peaksnail** [comment]
@den-crane It happened when I alter table bill or goods_invocing, I show the last ch log when I alter table goods_invocing.
it's ReplacingMergeTree Engine

**Comment by alexey-milovidov** [comment]
I confirm, updating to 20.6 will help.
ALTER queries are 100% lock-free* since 20.6.

\* lock-free means that they don't use table-level locks, only small locks on data structures that cannot block queries.

**Comment by peaksnail** [comment]
hi
the lock still exists on the version 20.6

ch version 20.6.6.7

log 
```
Received exception from server (version 20.6.6):
Code: 473. DB::Exception: Received from 172.18.122.58:7000. DB::Exception: WRITE locking attempt on "taotie.abacus_merchant_desktop" has timed out! (120000ms) Possible deadlock avoided. Client should retry.. 

0 rows in set. Elapsed: 120.041 sec. 

```

**Comment by woozhijun** [comment]
hi
the lock still exists on the version 21.3.6.55.

```
ERROR - Code: 473, e.displayText() = DB::Exception: WRITE locking attempt on "xxx" has timed out! (120000ms) Possible deadlock avoided. Client should retry. 
```

**Comment by injecto** [comment]
I'm not sure how is my issue related to the original one, but I have a pretty strange  DEADLOCK_AVOIDED that reproduced while automated migration, but isn't presented while manual execution of such batch:

```
ALTER TABLE convert_rate_log DROP INDEX insertion_time_index;
ALTER TABLE convert_rate_log ADD INDEX insertion_time_index insertion_time TYPE minmax GRANULARITY 200;
ALTER TABLE convert_rate_log MATERIALIZE INDEX insertion_time_index;
```

ClickHouse server version 22.1.3 revision 54455

```
DB::Exception: Locking attempt for ALTER on "db.convert_rate_log" has timed out! (120000 ms) Possible deadlock avoided. Client should retry. (DEADLOCK_AVOIDED) (version 22.1.3.7 (official build)) (from 127.0.0.1:48138) (in query:  ALTER TABLE convert_rate_log DROP INDEX insertion_time_index;)
```
