### ISSUE TITLE
Use HTTP trailers.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#21136]
If client supports HTTP 1.1, use trailers to provide progress, status and possibly error message.

**Use case**
This is the only way to return error in the middle of query processing if HTTP headers have been already sent.

**Comment by filimonov** [comment]
Significant limitation of that is that most of http clients don't have a good support of trailers, and reimplementing that may require hacking http client on quite a low level (chunked decoding).

Does poco support that?

**Comment by filimonov** [comment]
See also #6294 #208

**Comment by alexey-milovidov** [comment]
> Does poco support that?

No.

But we can send trailers only if client requested them:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/TE

**Comment by filimonov** [comment]
My IMHO: trailers are nice because they are part of http itself, and that's the only advanrage. Server-sent-events are simpler to implement, work great in browsers, has nice libs to work with in most of programming language, and can be reimplemented by any programmer in few hours without hacking http client (ot builing own http client).

**Comment by alexey-milovidov** [comment]
Is it possible to change HTTP status code (e.g. the server returns 200 Ok in header and change it to 500 Internal Server Error in trailer)?

**Comment by filimonov** [comment]
No. Status is the first line of the response, and can not be overwritten (while you of course can have some extra header / trailer like X-ClickHouse-Status).

BTW - here is a synthetic test case: http://w3c-test.org/xhr/getresponseheader-chunked-trailer.htm

```
telnet w3c-test.org 80
Trying 2603:400a:ffff:804:801e:36:0:8a...
Trying 128.30.54.138...
Connected to w3c-test.org.
Escape character is '^]'.
GET /xhr/resources/chunked.py HTTP/1.1
HTTP/1.1 200 OK
Transfer-Encoding: chunked
Trailer: X-Test-Me
Content-Type: text/plain
Server: BaseHTTP/0.6 Python/3.7.3
Date: Mon, 22 Feb 2021 09:34:48 GMT
d
First chunk
e
Second chunk
1b
Yet another (third) chunk
1c
Yet another (fourth) chunk
0
X-Test-Me: Trailer header value
Connection closed by foreign host.
```

The test explicitly checks that 
```
assert_equals(client.getResponseHeader('X-Test-Me'), null)
assert_equals(client.getAllResponseHeaders().indexOf('Trailer header value'), -1)
```

So trailer exists but not available (simply ignored), and you can not access it via XMLHttpRequest.

**Comment by alexey-milovidov** [comment]
Ok, then maybe close this issue in favor of server send events?

**Comment by filimonov** [comment]
Server sent events sounds much more useful for me. And don't require hacking the clients. I can imagine a lot of immediate applications of SSE, mostly browser based, starting from adding support for that in clickhouse demo.

**Comment by traceon** [comment]
@alexey-milovidov So what's the final decision on this? Adding a separate mode/format/switch that will make ClickHouse to respond in HTTP with Server-sent events? Does anyone work on adding this currently?

I would make use of this to properly implement #18689 (and/or #20490).

For the sake of completeness, there is also HTTP chunk extension mechanism, which allows `name=value` pairs prepended to each chunk (whereas the Trailer is just a header appended to the end of the last chunk of the body), but they are just too exotic so that even Curl doesn't parse them.

**Comment by chenziliang** [comment]
we have implemented something to stream back the progress status (bytes / row scan etc) via HTTP interface by using chunk format before sending the real query result. Clients need do some special parsing to decide if it is progress response or query result. It works pretty fine for us so far. If this solution sounds good, I can create a PR, may be extending that a bit to include other status like error reporting.

BTW, the status can be only `streamed` back before query result is produced. Once query result starts streaming back to HTTP client. No further status will be reported.

**Comment by traceon** [comment]
> BTW, the status can be only streamed back before query result is produced. Once query result starts streaming back to HTTP client, no further status will be reported and obviously this feature is only turned on by using a setting flag.

That's the same limitation we want to work around right now. Currently, the progress can be streamed in a form of HTTP headers, but that's possible only until the first byte of the body is transmitted, which limits the period of the query for which the progress can be reported.

**Comment by alexey-milovidov** [comment]
> Adding a separate mode/format/switch that will make ClickHouse to respond in HTTP with Server-sent events?

I imagined it as a framing format for server responses (activated by URL parameter).

But server sent events don't support binary data: https://stackoverflow.com/questions/33529685/using-sse-to-send-image-data
So, we cannot use it for arbitrary formats. It can find limited use for TSV/CSV/JSONEachRow (in fact, even these formats are binary in ClickHouse).

> Does anyone work on adding this currently?

No.

> So what's the final decision on this?

Still not sure.

**Comment by traceon** [comment]
> Maybe implement WebSockets protocol?

Boost has an implementation, by the way. On top of Boost.Asio. It has HTTP implementation too.

**Comment by traceon** [comment]
@alexey-milovidov By the way, if performance of the parsing is important inside a browser (and if relevant for the target use cases at all), another option to consider could be using native binary interface and adapting `clickhouse-cpp` to be compilable into WebAssembly for running inside a browser.

**Comment by traceon** [comment]
Actually, only the stream parsing is enough, and it is not hard to implement in a standalone C++ code. I also mean native wasm bytecode, not JS as a target.

**Comment by filimonov** [comment]
> Actually, only the stream parsing is enough, and it is not hard to implement in a standalone C++ code. I also mean native wasm bytecode, not JS as a target.

It's interesting as a research project but sounds too exotic / out of the scope for that particular issue.

We need a clean & standard way to talk clickhouse via HTTP (from a browser and other standard HTTP clients).

**Comment by filimonov** [comment]
> By the way, if performance of the parsing is important inside a browser

Not so important. In browsers typically only a small amount of data can be processed anyway. 

So anything reasonably good (better supported by browser natively) is ok. 

1) SSE: https://caniuse.com/eventsource 
2) base64: https://caniuse.com/atob-btoa
3) json: https://caniuse.com/json and speed of parsing JSON by calling JSON.parse is even better than JSON inlined in javascript and parsed by javascript interpreter (which is native): https://v8.dev/blog/cost-of-javascript-2019#json

**Comment by traceon** [comment]
> It's interesting as a research project but sounds too exotic / out of the scope for that particular issue.
We need a clean & standard way to talk clickhouse via HTTP (from a browser and other standard HTTP clients / without installing some strange stuff).

I understand your concerns, however, the thing with WASM is that it is not just "some strange stuff" :), it is supported out of the box in all major browsers, standardized, put a lot of academic effort into, and is the preferred/the only way of doing performance intensive things safely on client side. May not be the solution for the problems we are solving here, though. Or it may, I don't see a clear problem statement here.

> Not so important. In browsers typically only a small amount of data can be processed anyway.

That's the point, with WASM lots of data can be processed, with near-native performance. In the browser.

**Comment by filimonov** [comment]
Can you run wasm in curl? In Python http client? In perl http client? In Ruby http client? Etc.

**Comment by traceon** [comment]
> Can you run wasm in curl? In Python http client? In perl http client? In Ruby http client? Etc.

Well, you can't decode binary or BASE64 in curl too, etc. I guess, we are solving different problems here...

Regarding heavy calculations on client side: one example would be rendering data as plots.

**Comment by alexey-milovidov** [comment]
Trailers are not supported by either Firefox or Chrome in 2022:

https://bugzilla.mozilla.org/show_bug.cgi?id=1339096
https://bugs.chromium.org/p/chromium/issues/detail?id=691599

**Comment by den-crane** [comment]
Reverse proxies (nginx, traefik) and most of load balancers just strip the trailer headers, so a clients never receive them.
https://mailman.nginx.org/pipermail/nginx/2020-June/059547.html
