### ISSUE TITLE
MergeMutateRuntimeQueue Memory Limit Exceeded

### ISSUE THREAD

**Issue by MeteHanC** [ClickHouse/ClickHouse#40215]
Hi,

Version : **22.8.1.1545**

After upgrading to the latest version, we started getting this error out of nowhere. We were using 21.11.4.14 before. The configs and tables are all the same, we changed nothing. CH runs fine for 4-5 hours and then we get this error in the error logs : 

```

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) in /usr/bin/clickhouse
1. DB::Exception::Exception<char const*, char const*, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, long&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string_view<char, std::__1::char_traits<char> > >(int, fmt::v8::basic_format_string<char, fmt::v8::type_identity<char const*>::type, fmt::v8::type_identity<char const*>::type, fmt::v8::type_identity<char const*>::type, fmt::v8::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::type, fmt::v8::type_identity<long&>::type, fmt::v8::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::type, fmt::v8::type_identity<std::__1::basic_string_view<char, std::__1::char_traits<char> > >::type>, char const*&&, char const*&&, char const*&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, long&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, std::__1::basic_string_view<char, std::__1::char_traits<char> >&&) in /usr/bin/clickhouse
2. MemoryTracker::allocImpl(long, bool, MemoryTracker*) in /usr/bin/clickhouse
3. MemoryTracker::allocImpl(long, bool, MemoryTracker*) in /usr/bin/clickhouse
4. MemoryTracker::allocImpl(long, bool, MemoryTracker*) in /usr/bin/clickhouse
5. DB::Memory<Allocator<false, false> >::alloc() in /usr/bin/clickhouse
6. void std::__1::__function::__policy_invoker<void (DB::ISerialization::SubstreamPath const&)>::__call_impl<std::__1::__function::__default_alloc_func<DB::MergeTreeDataPartWriterCompact::addStreams(DB::NameAndTypePair const&, std::__1::shared_ptr<DB::IAST> const&)::$_0, void (DB::ISerialization::SubstreamPath const&)> >(std::__1::__function::__policy_storage const*, DB::ISerialization::SubstreamPath const&) in /usr/bin/clickhouse
7. DB::ISerialization::enumerateStreams(DB::ISerialization::SubstreamPath&, std::__1::function<void (DB::ISerialization::SubstreamPath const&)> const&, DB::ISerialization::SubstreamData const&) const in /usr/bin/clickhouse
8. DB::ISerialization::enumerateStreams(DB::ISerialization::SubstreamPath&, std::__1::function<void (DB::ISerialization::SubstreamPath const&)> const&, std::__1::shared_ptr<DB::IDataType const> const&) const in /usr/bin/clickhouse
9. DB::MergeTreeDataPartWriterCompact::addStreams(DB::NameAndTypePair const&, std::__1::shared_ptr<DB::IAST> const&) in /usr/bin/clickhouse
10. DB::MergeTreeDataPartWriterCompact::MergeTreeDataPartWriterCompact(std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, std::__1::shared_ptr<DB::IDataPartStorageBuilder>, DB::NamesAndTypesList const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeIndex const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeIndex const> > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::ICompressionCodec> const&, DB::MergeTreeWriterSettings const&, DB::MergeTreeIndexGranularity const&) in /usr/bin/clickhouse
11. DB::MergeTreeDataPartCompact::getWriter(std::__1::shared_ptr<DB::IDataPartStorageBuilder>, DB::NamesAndTypesList const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeIndex const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeIndex const> > > const&, std::__1::shared_ptr<DB::ICompressionCodec> const&, DB::MergeTreeWriterSettings const&, DB::MergeTreeIndexGranularity const&) const in /usr/bin/clickhouse
12. DB::MergedBlockOutputStream::MergedBlockOutputStream(std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, std::__1::shared_ptr<DB::IDataPartStorageBuilder>, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::NamesAndTypesList const&, std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeIndex const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeIndex const> > > const&, std::__1::shared_ptr<DB::ICompressionCodec>, std::__1::shared_ptr<DB::MergeTreeTransaction> const&, bool, bool, DB::WriteSettings const&) in /usr/bin/clickhouse
13. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::prepare() in /usr/bin/clickhouse
14. bool std::__1::__function::__policy_invoker<bool ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::MergeTask::ExecuteAndFinalizeHorizontalPart::subtasks::'lambda'(), bool ()> >(std::__1::__function::__policy_storage const*) in /usr/bin/clickhouse
15. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::execute() in /usr/bin/clickhouse
16. DB::MergeTask::execute() in /usr/bin/clickhouse
17. DB::MergePlainMergeTreeTask::executeStep() in /usr/bin/clickhouse
18. DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::routine(std::__1::shared_ptr<DB::TaskRuntimeData>) in /usr/bin/clickhouse
19. DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::threadFunction() in /usr/bin/clickhouse
20. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) in /usr/bin/clickhouse
21. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) in /usr/bin/clickhouse
22. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) in /usr/bin/clickhouse
23. void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) in /usr/bin/clickhouse
24. ? in ?
25. __clone in ?
 (version 22.8.1.1545 (official build))
2022.08.14 16:58:55.764565 [ 10860 ] {} <Error> void DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::routine(DB::TaskRuntimeDataPtr) [Queue = DB::MergeMutateRuntimeQueue]: Code: 241. DB::Exception: Memory limit (total) exceeded: would use 467.56 GiB (attempt to allocate chunk of 4289410 bytes), maximum: 15.54 GiB. OvercommitTracker decision: Memory overcommit isn't used. Waiting time or overcommit denominator are set to zero. (MEMORY_LIMIT_EXCEEDED), Stack trace (when copying this message, always include the lines below):
```

I think this is related to a background merge job fail, so here is the table details : 
Size :  **128 GB**
Rows : **5+ Billions**

Thanks in the advance

**Comment by ilya-zlobintsev** [comment]
Do you happen to be running Clickhouse in a containerized environment with memory limits? Until 21.12, the memory limit detection via cgroups wasn't working properly, so the memory limit was equal to the entire machine memory. 
It was fixed in https://github.com/ClickHouse/ClickHouse/pull/31157

**Comment by fernee** [comment]
@ilya-zlobintsev same problem running Clickhouse in a containerized environment with memory limits. my clickhosue version is `22.3.8.39`, and @MeteHanC 's version is `22.8.1.1545`, we both use a version after `21.12`, why cgroups memeory still not be respected?

**Comment by nikitamikhaylov** [comment]
Please, try to upgrade. 
There were a few PRs which will help to address huge memory usage for merges: https://github.com/ClickHouse/ClickHouse/pull/59340, https://github.com/ClickHouse/ClickHouse/pull/45681

You can also try to tune settings `merge_max_block_size` and `merge_max_block_size_bytes` or relax the conditions for vertical merge (the settings for them have prefix `vertical_merge_algorithm_*`).
