### ISSUE TITLE
Docker image with CLICKHOUSE_GID: DB::Exception: Group 0 is not found in the system

### ISSUE THREAD

**Issue by Kondratenko-Valeriy** [ClickHouse/ClickHouse#42400]
Since 22.6 docker image with ENVs CLICKHOUSE_UID=0 and CLICKHOUSE_GID=0 doesn't start:

```
# docker run --rm -e CLICKHOUSE_UID=0 -e CLICKHOUSE_GID=0 --name clickhouse-server clickhouse/clickhouse-server:22.6
Code: 36. DB::Exception: Group {} is not found in the system. (BAD_ARGUMENTS) (version 22.6.9.11 (official build))

# docker run --rm -e CLICKHOUSE_UID=0 -e CLICKHOUSE_GID=0 --name clickhouse-server clickhouse/clickhouse-server:22.7
Code: 36. DB::Exception: Group 0 is not found in the system. (BAD_ARGUMENTS) (version 22.7.6.74 (official build))

# docker run --rm -e CLICKHOUSE_UID=0 -e CLICKHOUSE_GID=0 --name clickhouse-server clickhouse/clickhouse-server:22.8
Code: 36. DB::Exception: Group 0 is not found in the system. (BAD_ARGUMENTS) (version 22.8.6.71 (official build))

# docker run --rm -e CLICKHOUSE_UID=0 -e CLICKHOUSE_GID=0 --name clickhouse-server clickhouse/clickhouse-server:22.9
Code: 36. DB::Exception: Group 0 is not found in the system. (BAD_ARGUMENTS) (version 22.9.3.18 (official build))
```

Error `Group {} is not found in the system` seen in version 22.6 has been fixed in https://github.com/ClickHouse/ClickHouse/issues/38583 and after that error message changed to `Group 0 is not found in the system`.

**Comment by luugh** [comment]
I checked the container's startup script and tried to replace 0 with root. It started successfully. You can also try

**Comment by dmlond** [comment]
at one point clickhouse images worked in openshift (see  issue #11003). But newer versions do not work.

**Comment by ibotty** [comment]
I could make it run using
```
.spec.containers[0].command:
            - /bin/bash
            - -c
            - sed 's/id -g/id -gn/' /entrypoint.sh > /tmp/entrypoint.sh; exec bash /tmp/entrypoint.sh
```
i.e replacing the `id -g` call in the entrypoint by `id -gn`.  I don't think that's the proper solution though.  It works with Openshift/OKD though.

I assume that https://github.com/ClickHouse/ClickHouse/blob/54f660bd4fed8a711fdad5d91b7ceb4d940245f9/programs/su/su.cpp#L58 should be fixed though.

**Comment by alexey-milovidov** [comment]
The issue is still relevant, but it will be easy to fix.

**Comment by WasimIsmail** [comment]
@alexey-milovidov can this be fixed soon please if its easy?
we need to deploy latest version of clickhouse in our OCP and this is a blocker

**Comment by anvaari** [comment]
Workaround provided by @ibotty worked for me on Openshift using Altinity Operator

**Comment by sas1024** [comment]
Any news? For now all docker images from 22.6 still not working with CLICKHOUSE_UID=0 and CLICKHOUSE_GID=0

**Comment by l33tlamer** [comment]
Confirmed still not working in current image clickhouse/clickhouse-server:23.9.1.1854-alpine

**Comment by alexey-milovidov** [comment]
@WasimIsmail, this issue is easy to fix.

**Comment by alexey-milovidov** [comment]
@ibotty, Could you please submit a pull request?

**Comment by alexey-milovidov** [comment]
@l33tlamer, this task is easy to implement, please submit a pull request.

**Comment by alexey-milovidov** [comment]
We need to find an enthusiast to solve this task.

**Comment by anvaari** [comment]
> We need to find an enthusiast to solve this task.

@alexey-milovidov I like to work on it, but I can't understand why you declined [this PR](https://github.com/ClickHouse/ClickHouse/pull/42270)

**Comment by alexey-milovidov** [comment]
It is very difficult to understand: https://github.com/ClickHouse/ClickHouse/pull/42270/files

If we do it like this:
```
id --group --name
```
it will be better.

Then add comments - what is happening and why, on this line of the shell script.

**Comment by alexey-milovidov** [comment]
Also, the comment: why we use the --name parameter for the group, but not for the user, remains.

**Comment by alexey-milovidov** [comment]
Also let's think - how exactly we will test this code.

**Comment by anvaari** [comment]
> Also let's think - how exactly we will test this code.
> 
> I hate all the code without comments. Also, I hate all the code without tests.

Yes it make sens. We can't explain why we changed it and also we can't test this on other environments.

I will work on it and will try to send proper PR

**Comment by anvaari** [comment]
I find out [`getgrnam_r`](https://linux.die.net/man/3/getgrnam_r) which used  [here](https://github.com/ClickHouse/ClickHouse/blob/54f660bd4fed8a711fdad5d91b7ceb4d940245f9/programs/su/su.cpp#L58C22-L58C32)  only accept group name not id. I couldn't find out why this work on environments other than OKD4. I'm still working on it

**Comment by Felixoid** [comment]
I am trying to address it by a simple fallback to the `getgruid_r` in #71626

**Comment by Felixoid** [comment]
Be aware that soon (in a couple of releases) `CLICKHOUSE_UID=0` and `CLICKHOUSE_GID=0` will be noop. To have the same behavior, one must use `CLICKHOUSE_RUN_AS_ROOT=1`.
