### ISSUE TITLE
 clickhouse clusters will restart every once in a while,

### ISSUE THREAD

**Issue by Caius1L** [ClickHouse/ClickHouse#46634]
One of the clickhouse clusters will restart every once in a while, and it will display kill -11 in the log. There are no other errors when checking the clickhouse and system logs. Has anyone encountered the same problem?

**Comment by Caius1L** [comment]
![image](https://user-images.githubusercontent.com/41660881/220277817-fd5bdc5e-85c0-4704-b914-8ec265f18142.png)

**Comment by tavplubix** [comment]
Please share the following part of the log (as text, not as a screenshot, you can use https://pastila.nl/):
```
zgrep -Fa "<Fatal>" /var/log/clickhouse-server/*
```

Also version 22.3.**3** is obsolete, the latest patch release in 22.3 branch is 22.3.**20**, you should upgrade.

**Comment by Caius1L** [comment]
> zgrep -Fa "<Fatal>" /var/log/clickhouse-server/*

hey，this my log

**Comment by Caius1L** [comment]
> Please share the following part of the log (as text, not as a screenshot, you can use https://pastila.nl/):
> 
> ```
> zgrep -Fa "<Fatal>" /var/log/clickhouse-server/*
> ```
> 
> Also version 22.3.**3** is obsolete, the latest patch release in 22.3 branch is 22.3.**20**, you should upgrade.




This is the log I output according to the instructions, can you help me analyze the possible reasons? thanks buddy 

**[root@bigdata01 ~]#zgrep -Fa "<Fatal>" /var/log/clickhouse-server/*
/var/log/clickhouse-server/clickhouse-server.err.log:2022.12.02 21:42:23.423729 [ 1231 ] {} <Fatal> Application: Child process was terminated by signal 11.
/var/log/clickhouse-server/clickhouse-server.err.log:2023.02.17 11:26:13.270268 [ 10314 ] {} <Fatal> Application: Child process was terminated by signal 11.**

**Comment by Caius1L** [comment]
> https://pastila.nl/

There will not be any other fatal logs before the sign -11, which makes me feel strange and confused

**Comment by tavplubix** [comment]
You can try to attach gdb to capture the stacktrace, but I would recommend upgrading first and checking if it's already fixed in the newer patch release. Also, 22.3 is the oldest of the supported [branches](https://github.com/ClickHouse/ClickHouse/pulls?q=is%3Aopen+is%3Apr+label%3Arelease), and its support ends in one month, so consider upgrading to 22.8 (the next LTS version).

**Comment by Caius1L** [comment]
> You can try to attach gdb to capture the stacktrace, but I would recommend upgrading first and checking if it's already fixed in the newer patch release. Also, 22.3 is the oldest of the supported [branches](https://github.com/ClickHouse/ClickHouse/pulls?q=is%3Aopen+is%3Apr+label%3Arelease), and its support ends in one month, so consider upgrading to 22.8 (the next LTS version).

Thank you buddy, we are already considering upgrading our production version, but we still want to check what is the cause of this issue. I have checked most of the problems, and it seems that there are not many reasons similar to ours.

**Comment by den-crane** [comment]
22.3.3 has a major issues. For example merges are broken. Nobody ever should use 22.3.3.

* https://github.com/ClickHouse/ClickHouse/issues/36687

**Comment by Caius1L** [comment]
> 22.3.3 存在重大问题。例如，合并被破坏。没有人应该使用 22.3.3。
> 
> * [22.4 宽部分的垂直合并被破坏 #36687](https://github.com/ClickHouse/ClickHouse/issues/36687)

I followed your suggestion to upgrade the version to 23.2, but we still have the problem of automatic restart after running for a while, it seems that the problem has not been solved
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.02 17:07:24.153054 [ 14261 ] {} <Fatal> Application: Child process was terminated by signal 11.
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.09 03:58:06.318437 [ 7932 ] {} <Fatal> BaseDaemon: ########################################
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.09 03:58:06.324868 [ 7932 ] {} <Fatal> BaseDaemon: (version 23.2.1.2537 (official build), build id: 50BDF08E4BF0B9023E0CA4AEFD09296FFEFF146B) (from thread 25132) (query_id: 5d853e85-a7df-49f5-9e98-1127dcddd9b6) (query: SELECT id, node_id, monitor_item, monitor_value, monitor_time FROM node_data WHERE node_id = 1 AND monitor_item = 'rain' AND monitor_time >= '2022-11-21 02:00:00' AND monitor_time < '2022-11-21 03:00:00' AND toFloat64(monitor_value) IS NOT NULL AND tenant_code = 'gpladz' ORDER BY monitor_time ASC LIMIT 1) Received signal Segmentation fault (11)
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.09 03:58:06.324907 [ 7932 ] {} <Fatal> BaseDaemon: Address: 0x7fb8f134d0f0 Access: read. Attempted access has violated the permissions assigned to the memory area.
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.09 03:58:06.324915 [ 7932 ] {} <Fatal> BaseDaemon: Stack trace: 0x1a1e515f 0x1a1e4387 0x1a1e3dbe 0xe0cbc29 0xe0ee8ad 0x7fb9fff2f630 0x1a1e3fd1 0x14628fd9 0x12259990
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.09 03:58:07.218346 [ 7932 ] {} <Fatal> BaseDaemon: 2. ./build_docker/../contrib/libunwind/src/DwarfInstructions.hpp:0: libunwind::DwarfInstructions<libunwind::LocalAddressSpace, libunwind::Registers_x86_64>::getSavedRegister(libunwind::LocalAddressSpace&, libunwind::Registers_x86_64 const&, unsigned long, libunwind::CFI_Parser<libunwind::LocalAddressSpace>::RegisterLocation const&) @ 0x1a1e515f in /usr/lib/debug/usr/bin/clickhouse.debug
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.09 03:58:07.238988 [ 7932 ] {} <Fatal> BaseDaemon: 3.1. inlined from ./build_docker/../contrib/libunwind/src/Registers.hpp:408: libunwind::Registers_x86_64::setRegister(int, unsigned long)
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.09 03:58:07.239008 [ 7932 ] {} <Fatal> BaseDaemon: 3. ./build_docker/../contrib/libunwind/src/DwarfInstructions.hpp:264: libunwind::DwarfInstructions<libunwind::LocalAddressSpace, libunwind::Registers_x86_64>::stepWithDwarf(libunwind::LocalAddressSpace&, unsigned long, unsigned long, libunwind::Registers_x86_64&, bool&) @ 0x1a1e4387 in /usr/lib/debug/usr/bin/clickhouse.debug
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.09 03:58:07.268533 [ 7932 ] {} <Fatal> BaseDaemon: 4.1. inlined from ./build_docker/../contrib/libunwind/src/UnwindCursor.hpp:1002: libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_x86_64>::stepWithDwarfFDE()
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.09 03:58:07.268557 [ 7932 ] {} <Fatal> BaseDaemon: 4. ./build_docker/../contrib/libunwind/src/UnwindCursor.hpp:2811: libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_x86_64>::step() @ 0x1a1e3dbe in /usr/lib/debug/usr/bin/clickhouse.debug
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.09 03:58:07.639071 [ 7932 ] {} <Fatal> BaseDaemon: 5.1. inlined from ./build_docker/../contrib/libunwind/src/libunwind.cpp:350: unw_backtrace
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.09 03:58:07.639094 [ 7932 ] {} <Fatal> BaseDaemon: 5.2. inlined from ./build_docker/../src/Common/StackTrace.cpp:336: StackTrace::tryCapture()
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.09 03:58:07.639102 [ 7932 ] {} <Fatal> BaseDaemon: 5. ./build_docker/../src/Common/StackTrace.cpp:302: StackTrace::StackTrace(ucontext_t const&) @ 0xe0cbc29 in /usr/lib/debug/usr/bin/clickhouse.debug
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.09 03:58:07.702517 [ 7932 ] {} <Fatal> BaseDaemon: 6. ./build_docker/../src/Common/QueryProfiler.cpp:70: DB::(anonymous namespace)::writeTraceInfo(DB::TraceType, int, siginfo_t*, void*) @ 0xe0ee8ad in /usr/lib/debug/usr/bin/clickhouse.debug
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.09 03:58:07.702570 [ 7932 ] {} <Fatal> BaseDaemon: 7. ? @ 0xf630 in /usr/lib64/libpthread-2.17.so
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.09 03:58:07.704047 [ 7932 ] {} <Fatal> BaseDaemon: 8. ./build_docker/../contrib/libunwind/src/UnwindCursor.hpp:2610: libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_x86_64>::setInfoBasedOnIPRegister(bool) @ 0x1a1e3fd1 in /usr/lib/debug/usr/bin/clickhouse.debug
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.09 03:58:08.858029 [ 7932 ] {} <Fatal> BaseDaemon: 9.1. inlined from ./build_docker/../src/Client/PacketReceiver.h:135: DB::PacketReceiver::Routine::operator()(boost::context::fiber&&)
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.09 03:58:08.908519 [ 7932 ] {} <Fatal> BaseDaemon: 9.2. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<DB::PacketReceiver::Routine&>()(std::declval<boost::context::fiber>())) std::__1::__invoke[abi:v15000]<DB::PacketReceiver::Routine&, boost::context::fiber>(DB::PacketReceiver::Routine&, boost::context::fiber&&)
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.09 03:58:08.908577 [ 7932 ] {} <Fatal> BaseDaemon: 9.3. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__functional/invoke.h:531: std::__1::invoke_result<DB::PacketReceiver::Routine&, boost::context::fiber>::type std::__1::invoke<DB::PacketReceiver::Routine&, boost::context::fiber>(DB::PacketReceiver::Routine&, boost::context::fiber&&)
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.09 03:58:08.908599 [ 7932 ] {} <Fatal> BaseDaemon: 9.4. inlined from ./build_docker/../contrib/boost/boost/context/fiber_fcontext.hpp:140: boost::context::detail::fiber_record<boost::context::fiber, FiberStack&, DB::PacketReceiver::Routine>::run(void*)
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.09 03:58:08.908620 [ 7932 ] {} <Fatal> BaseDaemon: 9. ./build_docker/../contrib/boost/boost/context/fiber_fcontext.hpp:80: void boost::context::detail::fiber_entry<boost::context::detail::fiber_record<boost::context::fiber, FiberStack&, DB::PacketReceiver::Routine>>(boost::context::detail::transfer_t) @ 0x14628fd9 in /usr/lib/debug/usr/bin/clickhouse.debug
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.09 03:58:09.058325 [ 7932 ] {} <Fatal> BaseDaemon: 10.1. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:174: std::__1::__shared_count::__release_shared[abi:v15000]()
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.09 03:58:09.058350 [ 7932 ] {} <Fatal> BaseDaemon: 10.2. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:215: std::__1::__shared_weak_count::__release_shared[abi:v15000]()
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.09 03:58:09.058359 [ 7932 ] {} <Fatal> BaseDaemon: 10.3. inlined from ./build_docker/../contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:702: ~shared_ptr
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.09 03:58:09.058364 [ 7932 ] {} <Fatal> BaseDaemon: 10. ./build_docker/../src/Storages/System/StorageSystemGraphite.cpp:11: DB::StorageSystemGraphite::getNamesAndTypes() @ 0x12259990 in /usr/lib/debug/usr/bin/clickhouse.debug
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.09 03:58:11.369757 [ 7932 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: E9EEDE564FADE8C5C10B54D957E56740)
/var/log/clickhouse-server/clickhouse-server.err.log:2023.04.09 03:58:26.964425 [ 15054 ] {} <Fatal> Application: Child process was terminated by signal 11.

![image](https://user-images.githubusercontent.com/41660881/230837093-d9144db4-2805-4c49-9405-19fb0010edfa.png)

**Comment by Caius1L** [comment]
> 您可以尝试附加 gdb 来捕获堆栈跟踪，但我建议先升级并检查它是否已在较新的补丁版本中修复。此外，22.3 是支持的[分支](https://github.com/ClickHouse/ClickHouse/pulls?q=is%3Aopen+is%3Apr+label%3Arelease)中最古老的分支，其支持将在一个月内结束，因此请考虑升级到 22.8（下一个 LTS 版本）。

I upgraded my version and still have the problem of restarting, but this time there are more logs than before, can you help me analyze the potential problem

**Comment by Caius1L** [comment]
> 22.3.3 存在重大问题。例如，合并被破坏。没有人应该使用 22.3.3。
> 
> * [22.4 宽部分的垂直合并被破坏 #36687](https://github.com/ClickHouse/ClickHouse/issues/36687)

can you help me analyze the potential problem

**Comment by xiaowuyy** [comment]
I meet the problem clickhouse version is 23.8.2.7
