### ISSUE TITLE
bug(s) in log writing failure handling

### ISSUE THREAD

**Issue by defhacks** [ClickHouse/ClickHouse#68438]
**Describe the unexpected behaviour**
when clickhouse attempts to log to a full disk, the code that appears to be intended to handle this case is never triggered, and the logging internals will not recover without a restart

**How to reproduce**
* I tested with the latest master at the time (5881f28718b63352f41637f0a89431aab9f71d70)
* relevant config.xml snippet:
```
  <logger>
        <level>trace</level>
        <console>false</console>
        <log>/tmp/ch_logs/clickhouse-server.log</log>
        <errorlog>/tmp/ch_logs/clickhouse-server.err.log</errorlog>
        <size>100M</size>
        <count>10</count>
    </logger>
```

where `/tmp/ch_logs` is a 32M disk made with:

```
dd if=/dev/zero of=/tmp/logs.img bs=1M count=32
mkfs.ext4 /tmp/logs.img
mount /tmp/logs.img /tmp/ch_logs
```
and to trigger the behaviour I'm running a `SELECT 1` every 5 second to just create some logs and then also running:

```
dd if=/dev/urandom of=/tmp/ch_logs/fill bs=1 ; sleep 15 ; rm /tmp/ch_logs/fill
```

to fill and recover the disk.

**Expected behavior**
error logging to stderr while disk is full and a return to regular logging after space is cleared

**Error message and/or stacktrace**
```
Cannot add message to the log: Processed in 0.000989522 sec.
Poco::Exception. Code: 1000, e.code() = 0, File access error: /tmp/ch_logs/clickhouse-server.log, Stack trace (when copying this message, always include the lines below):

0. ./contrib/llvm-project/libcxx/include/exception:141: Poco::Exception::Exception(String const&, int) @ 0x000000001489b812
1. ./build/./base/poco/Foundation/src/Exception.cpp:166: Poco::FileException::FileException(String const&, int) @ 0x00000000148a1b69
2. ./base/poco/Foundation/src/LogFile_STD.cpp:59: Poco::LogFileImpl::sizeImpl() const @ 0x00000000148bdc79
3. ./build/./base/poco/Foundation/src/RotateStrategy.cpp:109: Poco::RotateBySizeStrategy::mustRotate(Poco::LogFile*) @ 0x00000000148dfc6d
4. ./build/./base/poco/Foundation/src/FileChannel.cpp:111: Poco::FileChannel::log(Poco::Message const&) @ 0x00000000148a98e9
5. ./build/./src/Loggers/OwnFormattingChannel.cpp:0: DB::OwnFormattingChannel::logExtended(DB::ExtendedLogMessage const&) @ 0x000000000bf0dcae
6. ./build/./src/Loggers/OwnSplitChannel.cpp:87: DB::OwnSplitChannel::logSplit(Poco::Message const&) @ 0x000000000bf11819
7. ./build/./src/Loggers/OwnSplitChannel.cpp:0: DB::OwnSplitChannel::tryLogSplit(Poco::Message const&) @ 0x000000000bf11689
8. ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:701: DB::OwnSplitChannel::log(Poco::Message const&) @ 0x000000000bf11596
9. ./build/./src/Server/TCPHandler.cpp:0: DB::TCPHandler::runImpl()::$_1::operator()() const @ 0x0000000011ca3136
10. ./build/./src/Server/TCPHandler.cpp:0: DB::TCPHandler::runImpl() @ 0x0000000011c985a7
11. ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:593: DB::TCPHandler::run() @ 0x0000000011caf2f9
12. ./build/./base/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0x0000000014940227
13. ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:48: Poco::Net::TCPServerDispatcher::run() @ 0x00000000149406fa
14. ./build/./base/poco/Foundation/src/ThreadPool.cpp:219: Poco::PooledThread::run() @ 0x00000000148ebc72
15. ./base/poco/Foundation/include/Poco/SharedPtr.h:139: Poco::ThreadImpl::runnableEntry(void*) @ 0x00000000148e9763
16. ? @ 0x00007efd8529ca94
17. ? @ 0x00007efd85329c3c
 (version 24.8.1.1)
```

**Additional context**

This appears to have also surfaced as #66347 but I don't think the reporter provided the details about how actual and expected behaviour differed.

The following patch seems to yield the expected behaviour, but I'm not sure if this causes other issues instead. Also of note is that without this change the stack trace included above repeats until restart and `errno`/`e.code()` is always `0` as opposed to `28`/`ENOSPC`. With the patch applied there is an initial stack trace that has `errno` of `0`, but the subsequent errors seem much clearer.

```
diff --git a/base/poco/Foundation/src/LogFile_STD.cpp b/base/poco/Foundation/src/LogFile_STD.cpp
index 034ccabfb62..67700a65308 100644
--- a/base/poco/Foundation/src/LogFile_STD.cpp
+++ b/base/poco/Foundation/src/LogFile_STD.cpp
@@ -55,8 +55,10 @@ void LogFileImpl::writeBinaryImpl(const char * data, size_t size, bool flush)

 UInt64 LogFileImpl::sizeImpl() const
 {
-       if (!_str.good())
-               throw FileException(_path);
+       if (!_str.good()) {
+               _str.clear();
+               throw FileException("error getting size", _path, errno);
+       }
        return (UInt64) _str.tellp();
 }
```

**Comment by casadomusdev** [comment]
@defhacks appreciate the sleuth work!  have u still got your patch in place after over a year has passed?  i definitely confirm this bug report, had this happen spectacularly for us today!  would apply your patch, but it really seems like this should be fixed upstream..??

**Comment by hashiromer** [comment]
Still reproducible on **26.5.2.39 (official build)**, and on `clickhouse-server` (not just keeper, cf. #101444).

A data disk filled up, and from that point the in-process logging channel was permanently wedged exactly as described here — it never recovered after space was freed, only a process restart fixed it.

Observed behaviour:
- Every log attempt threw the same exception, emitted to stderr and captured by journald/rsyslog into `/var/log/syslog`:

```
clickhouse-server[554463]: Cannot log message in OwnAsyncSplitChannel channel: Poco::Exception. Code: 1000, e.code() = 0, File access error: /var/log/clickhouse-server/clickhouse-server.log, Stack trace (when copying this message, always include the lines below):
clickhouse-server[554463]: 0. Poco::RotateBySizeStrategy::mustRotate(Poco::LogFile*) @ 0x0000000022f57c43
clickhouse-server[554463]: 1. Poco::CombinedRotateStrategy::mustRotate(Poco::LogFile*) @ 0x0000000022f3587d
clickhouse-server[554463]: 2. Poco::FileChannel::log(Poco::Message const&) @ 0x0000000022f31389
clickhouse-server[554463]: 3. DB::OwnFormattingChannel::logExtended(DB::ExtendedLogMessage const&) @ 0x000000001e395d19
clickhouse-server[554463]: 4. DB::OwnRunnableForChannel::run() @ 0x000000001e39fa21
clickhouse-server[554463]: 5. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000022f5e98f
```

- **Crucially, freeing disk space did not recover it.** With the data partition no longer full and the log directory writable (`clickhouse` user could write the file, perms `drwxrwx--- clickhouse:clickhouse`, current `.log` a valid 0-byte file), the running process kept throwing on every log call. `/var/log/syslog` grew back at ~8–10 MB/s and re-filled the disk within minutes of being truncated.
- The only thing that stopped it was stopping the `clickhouse-server` process. A fresh process logs fine.

**Comment by groeneai** [comment]
Not a crash: a `Poco` exception thrown inside the logging channel and caught. Two distinct bugs, one fixed and one still open on master.

**1. Logging never recovers. Fixed.**

`Poco::LogFileImpl::writeImpl` and `writeBinaryImpl` now clear the stream error flags before throwing, so the next rotation check (`FileChannel::log` -> `RotateBySizeStrategy::mustRotate` -> `LogFile::size` -> `sizeImpl`) stops throwing forever. That is #93127, merged 2026-07-02, first released in `v26.7.1.1315-stable`. `base/poco/Foundation/src/LogFile_STD.cpp` carries the two `_str.clear()` calls on `26.7` and `26.8`, and does not on `26.3` or `26.6`. Every version reported here predates the fix (`24.8.1.1`, and `26.5.2.39` tested 2026-06-23), so none of the confirmations above tested it.

I re-ran the reproducer from the report on `26.9.1.1` (32M ext4 loop mount, fill with `dd`, then `rm`). While full, the `ENOSPC` branch of `FileChannel::log` truncated the log from 91514 to 5577 bytes; after freeing space the log grew 82645 bytes in 20s and stderr got 0 bytes. Recovery works.

**2. Any non-`ENOSPC` write failure escapes the handler and amplifies to stderr without bound. Still open.**

`Poco::FileStreamBuf::writeToDevice` (`FileStream_POSIX.cpp:94`) reports a failed `write` by throwing from inside the stream insertion, and `FileImpl::handleLastErrorImpl` (`File_UNIX.cpp:488`) picks the type from `errno`: `EPERM`/`EACCES` give `FileAccessDeniedException`, `ENOSPC`/`EDQUOT` give a plain `FileException`, `EROFS` gives `FileReadOnlyException`. None of those is a `WriteFileException`, the only type `FileChannel::log` catches (`FileChannel.cpp:133`), and that handler also acts only on `errno == ENOSPC` (`:142`). So the exception leaves the channel and `OwnSplitChannel` / `OwnAsyncSplitChannel` write the message plus the whole formatted exception, stack trace included, to stderr on every log call, with no rate limit and no deduplication (`OwnSplitChannel.cpp:214`, `:630`).

Measured on `26.9.1.1` using the condition @ crest42 described (`chattr +i` on the log file): 376 identical `FileAccessDeniedException` stack traces in 15s, 1194928 bytes of stderr, about 80 KB/s. This is the mechanism behind the disk exhaustion reported here, and it is independent of #93127. It also explains the divergent reports here: a full disk is now handled silently, an unwritable file is not handled at all.

**Owner.** Defensible. What is left sits in `src/Loggers/OwnSplitChannel.cpp` and `base/poco/Foundation/src/FileChannel.cpp`; `src/Loggers/**` is a `comp-logging` signal and @ azat is a listed `comp-logging` expert. The recent commits on both files are @ alexey-milovidov's.

**Suggested fix**, root cause before mitigation:

- In `FileChannel::log`, catch `Poco::FileException` instead of `WriteFileException` and branch on `e.code()`, which Poco already fills, rather than re-reading `errno` in the handler. The `NOTE` at `FileChannel.cpp:138` already records that re-read as a workaround.
- Pass `errno` at the three throw sites that drop it. `writeImpl`, `writeBinaryImpl` and `sizeImpl` all construct with no code, which is why `e.code() = 0` in the original report. That was the other half of @ defhacks' patch; only the `clear()` half was taken.
- Then bound the stderr fallback, because a log file that stays unwritable still turns one log line into a stack trace per message.

For `26.3` and `26.6` the recovery fix needs a backport label on #93127.

I can open a PR for the first two points if that shape looks right.
