### ISSUE TITLE
Iceberg sets incorrect filter dag when reading a parquet which schema was changed

### ISSUE THREAD

**Issue by divanik** [ClickHouse/ClickHouse#85029]
### Describe what's wrong

```
E           helpers.client.QueryRuntimeException: Client failed! Return code: 32, stderr: [node1] 2025.08.04 12:22:36.160067 [ 695 ] {70cf1b5f-edca-4f95-82fb-1ba52900f88c} <Fatal> : Logical error: 'Hyperrectangle size is 1, but requested element at posittion 1 ((column 1 in [2, +Inf)))'.
E           [node1] 2025.08.04 12:22:36.174588 [ 695 ] {70cf1b5f-edca-4f95-82fb-1ba52900f88c} <Fatal> : Stack trace (when copying this message, always include the lines below):
E           
E           0. /home/divanik-work/ClickHouseClone2/ClickHouse/contrib/llvm-project/libcxx/include/__exception/exception.h:113: Poco::Exception::Exception(String const&, int) @ 0x00000000241a9232
E           1. /home/divanik-work/ClickHouseClone2/ClickHouse/src/Common/Exception.cpp:116: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x0000000012146cdb
E           2. /home/divanik-work/ClickHouseClone2/ClickHouse/src/Common/Exception.h:119: DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000b12d2ac
E           3. /home/divanik-work/ClickHouseClone2/ClickHouse/src/Common/Exception.h:137: DB::Exception::Exception<unsigned long, unsigned long const&, String>(int, FormatStringHelperImpl<std::type_identity<unsigned long>::type, std::type_identity<unsigned long const&>::type, std::type_identity<String>::type>, unsigned long&&, unsigned long const&, String&&) @ 0x000000001bb92eeb
E           4. /home/divanik-work/ClickHouseClone2/ClickHouse/src/Storages/MergeTree/KeyCondition.cpp:3241: DB::KeyCondition::checkInHyperrectangle(std::vector<DB::Range, std::allocator<DB::Range>> const&, std::vector<std::shared_ptr<DB::IDataType const>, std::allocator<std::shared_ptr<DB::IDataType const>>> const&, std::unordered_map<unsigned long, std::unique_ptr<DB::KeyCondition::BloomFilter, std::default_delete<DB::KeyCondition::BloomFilter>>, std::hash<unsigned long>, std::equal_to<unsigned long>, std::allocator<std::pair<unsigned long const, std::unique_ptr<DB::KeyCondition::BloomFilter, std::default_delete<DB::KeyCondition::BloomFilter>>>>> const&) const @ 0x000000001bb8a09f
E           5. /home/divanik-work/ClickHouseClone2/ClickHouse/src/Processors/Formats/Impl/ParquetBlockInputFormat.cpp:770: DB::ParquetBlockInputFormat::initializeIfNeeded()::$_4::operator()(int) const @ 0x000000001c569892
E           6. /home/divanik-work/ClickHouseClone2/ClickHouse/src/Processors/Formats/Impl/ParquetBlockInputFormat.cpp:780: DB::ParquetBlockInputFormat::initializeIfNeeded() @ 0x000000001c566885
E           7. /home/divanik-work/ClickHouseClone2/ClickHouse/src/Processors/Formats/Impl/ParquetBlockInputFormat.cpp:1114: DB::ParquetBlockInputFormat::read() @ 0x000000001c56c9df
E           8. /home/divanik-work/ClickHouseClone2/ClickHouse/src/Processors/Formats/IInputFormat.cpp:18: DB::IInputFormat::generate() @ 0x000000001c3e02d6
E           9. /home/divanik-work/ClickHouseClone2/ClickHouse/src/Processors/ISource.cpp:147: DB::ISource::tryGenerate() @ 0x000000001c3b63da
E           10. /home/divanik-work/ClickHouseClone2/ClickHouse/src/Processors/ISource.cpp:110: DB::ISource::work() @ 0x000000001c3b60b6
E           11. /home/divanik-work/ClickHouseClone2/ClickHouse/src/Processors/Executors/ExecutionThreadContext.cpp:53: DB::ExecutionThreadContext::executeTask() @ 0x000000001c3d23bb
E           12. /home/divanik-work/ClickHouseClone2/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:350: DB::PipelineExecutor::executeStepImpl(unsigned long, DB::IAcquiredSlot*, std::atomic<bool>*) @ 0x000000001c3c5677
E           13. /home/divanik-work/ClickHouseClone2/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:179: DB::PipelineExecutor::executeStep(std::atomic<bool>*) @ 0x000000001c3c4e3e
E           14. /home/divanik-work/ClickHouseClone2/ClickHouse/src/Processors/Executors/PullingPipelineExecutor.cpp:59: DB::PullingPipelineExecutor::pull(DB::Chunk&) @ 0x000000001c3db0dc
E           15. /home/divanik-work/ClickHouseClone2/ClickHouse/src/Storages/ObjectStorage/StorageObjectStorageSource.cpp:285: DB::StorageObjectStorageSource::generate() @ 0x000000001746b487
E           16. /home/divanik-work/ClickHouseClone2/ClickHouse/src/Processors/ISource.cpp:147: DB::ISource::tryGenerate() @ 0x000000001c3b63da
E           17. /home/divanik-work/ClickHouseClone2/ClickHouse/src/Processors/ISource.cpp:110: DB::ISource::work() @ 0x000000001c3b60b6
E           18. /home/divanik-work/ClickHouseClone2/ClickHouse/src/Processors/Executors/ExecutionThreadContext.cpp:53: DB::ExecutionThreadContext::executeTask() @ 0x000000001c3d23bb
E           19. /home/divanik-work/ClickHouseClone2/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:350: DB::PipelineExecutor::executeStepImpl(unsigned long, DB::IAcquiredSlot*, std::atomic<bool>*) @ 0x000000001c3c5677
E           20. /home/divanik-work/ClickHouseClone2/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:278: DB::PipelineExecutor::executeSingleThread(unsigned long, DB::IAcquiredSlot*) @ 0x000000001c3c5b9e
E           21. /home/divanik-work/ClickHouseClone2/ClickHouse/src/Processors/Executors/PipelineExecutor.cpp:561: void std::__function::__policy_invoker<void ()>::__call_impl[abi:se190107]<std::__function::__default_alloc_func<DB::PipelineExecutor::spawnThreads(std::shared_ptr<DB::IAcquiredSlot>)::$_0, void ()>>(std::__function::__policy_storage const*) @ 0x000000001c3c6583
E           22. /home/divanik-work/ClickHouseClone2/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x000000001228abf3
E           23. /home/divanik-work/ClickHouseClone2/ClickHouse/contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*>(void (ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool::*&&)(), ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::ThreadFromThreadPool*&&)::'lambda'()::operator()() @ 0x00000000122910e6
E           24. /home/divanik-work/ClickHouseClone2/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:716: ? @ 0x00000000122880c6
E           25. /home/divanik-work/ClickHouseClone2/ClickHouse/contrib/llvm-project/libcxx/include/__type_traits/invoke.h:117: void* std::__thread_proxy[abi:se190107]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void (ThreadPoolImpl<std::thread>::ThreadFromThreadPool::*)(), ThreadPoolImpl<std::thread>::ThreadFromThreadPool*>>(void*) @ 0x000000001228e940
E           26. ? @ 0x0000000000094ac3
E           27. ? @ 0x0000000000126850
```

### Does it reproduce on the most recent release?

Yes

### How to reproduce

```
@pytest.mark.parametrize("storage_type", ["s3", "azure", "local"])
def test_schema_evolution_with_where_condition(started_cluster, storage_type):
    instance = started_cluster.instances["node1"]
    spark = started_cluster.spark_session
    TABLE_NAME = "test_schema_evolution_with_where_condition_" + get_uuid_str()

    def execute_spark_query(query: str):
        return execute_spark_query_general(
            spark,
            started_cluster,
            storage_type,
            TABLE_NAME,
            query,
        )

    execute_spark_query(
        f"""
            DROP TABLE IF EXISTS {TABLE_NAME};
        """
    )

    execute_spark_query(
        f"""
            CREATE TABLE IF NOT EXISTS {TABLE_NAME} (
                a int
            )
            USING iceberg
            OPTIONS('format-version'='2')
        """
    )

    execute_spark_query(f"INSERT INTO {TABLE_NAME} VALUES (1)")

    execute_spark_query(f"ALTER TABLE {TABLE_NAME} ADD COLUMNS (b INT)")

    execute_spark_query(f"INSERT INTO {TABLE_NAME} VALUES (1, 2)")

    default_upload_directory(
        started_cluster,
        storage_type,
        f"/iceberg_data/default/{TABLE_NAME}/",
        f"/iceberg_data/default/{TABLE_NAME}/",
    )

    table_creation_expression = get_creation_expression(
        storage_type,
        TABLE_NAME,
        started_cluster,
        table_function=True,
        allow_dynamic_metadata_for_data_lakes=False,
    )

    table_select_expression = table_creation_expression

    print(f"Table select expression: {table_select_expression}")

    instance.query(f"SELECT * FROM {table_select_expression} WHERE b >= 2 ORDER BY ALL")
```

### Expected behavior

We need to adjust filter_dag to a correct parquet schema

**Comment by PedroTadim** [comment]
🕵️ 

Found what looks like the same defect from a different direction, with a pure-SQL repro (no Spark)
and a workaround. Posting here rather than opening a new issue because the title and the stated
fix — "adjust filter_dag to a correct parquet schema" — describe this exactly, but the symptom and
stack are different, so please split it out if you disagree.

### Second trigger: `MODIFY COLUMN` to `Nullable`

Making a required column optional is a legal Iceberg schema evolution, and ClickHouse's own `ALTER`
performs it. Filtering that column then aborts on the data written before the `ALTER`:

```bash
mkdir -p /tmp/iceberg_nullable_filter && cd /tmp/iceberg_nullable_filter

clickhouse local -q "
    SET allow_experimental_insert_into_iceberg = 1;
    SET allow_insert_into_iceberg = 1;
    CREATE TABLE t (id Int64, s String) ENGINE = IcebergLocal('lake/');
    INSERT INTO t SELECT number, toString(number) FROM numbers(5);
    ALTER TABLE t MODIFY COLUMN id Nullable(Int64);
"

clickhouse local -q "SELECT * FROM icebergLocal('lake/') WHERE id > 3"
```

```
Logical error: 'Unexpected return type from greater. Expected Nullable(UInt8). Got UInt8'

DB::executeActionForPartialResult      src/Interpreters/ActionsDAG.cpp
DB::ActionsDAG::evaluatePartialResult  src/Interpreters/ActionsDAG.cpp
DB::ActionsDAG::updateHeader           src/Interpreters/ActionsDAG.cpp
DB::FilterTransform::transformHeader   src/Processors/Transforms/FilterTransform.cpp:57
DB::FilterTransform::FilterTransform   src/Processors/Transforms/FilterTransform.cpp:82
```

### It is the PREWHERE move

The data path is fine — only the pushed-down predicate breaks:

| query | result |
| --- | --- |
| `SELECT id, toTypeName(id) FROM …` | `Nullable(Int64)`, correct |
| `SELECT countIf(id > 3) FROM …` | `1`, correct |
| `SELECT count() FROM (SELECT id FROM …) WHERE id > 3` | `1`, correct |
| `SELECT * FROM … WHERE id > 3` | **abort** |
| `SELECT * FROM … WHERE id > 3 SETTINGS optimize_move_to_prewhere = 0` | `4  4`, correct |
| `SELECT id FROM … PREWHERE id > 3` | **abort** |
| `SELECT id FROM … PREWHERE s = '4'` (untouched column) | correct |

`EXPLAIN PLAN header=1` shows the predicate moved into the source:

```
ReadFromObjectStorage
   Header: id Nullable(Int64)
           s String
   Prewhere filter column:  id > 3
```

The expression is type-checked against the evolved table schema — `id` is `Nullable`, so `greater`
declares `Nullable(UInt8)` — but it is evaluated inside the source against the physical file
schema, where `id` is still plain `Int64`, so `greater` yields `UInt8`. With
`optimize_move_to_prewhere = 0` the filter becomes a separate step above `ReadFromObjectStorage`,
where the header is already `Nullable(Int64)`, and it works. So PREWHERE is being pushed past the
schema-evolution transform.

`SET optimize_move_to_prewhere = 0` is a usable workaround; it returns the correct rows.

### Scope

Debug builds abort; release builds return the `LOGICAL_ERROR`, so the query fails either way.
Only comparison predicates on the evolved column are affected — `SELECT *`, `count()`, `sum(id)`,
`ORDER BY id`, `WHERE id IS NOT NULL` and filters on untouched columns all succeed, a table
declared `Nullable` from the start is fine, and data written after the `ALTER` is fine.

Not reproducible outside the data-lake read path: MergeTree (sync and async mutation, with
`apply_mutations_on_fly`), `VIEW`, materialized view, the `Merge` engine, `merge()`, `file()` with
a structure override and `remote()` are all clean. Alter conversions mean those sources always
present the declared schema, so the header and the plan cannot disagree — which is consistent with
this being specific to the lake reader.

### One caveat on the original repro

I could not reproduce the `ADD COLUMNS` case from the description on master — it returns the
correct rows. But I emulated it with ClickHouse's own `ALTER TABLE … ADD COLUMN` rather than Spark,
and the two writers do not produce identical metadata, so please do not read that as evidence the
original is fixed.

Tested on master `c462bd70270441b71070b4c5417a32e33cac0bab` (26.8.1.1154), `CMAKE_BUILD_TYPE=Debug`.

**Comment by PedroTadim** [comment]
@groeneai can you fix this issue if there is no PR already? Look at my comment as well

**Comment by groeneai** [comment]
@PedroTadim Confirmed, no PR fixes this. The nearest open ones are mine and are different mechanisms: #110920 (column pruning for schema-evolved reads, `StorageObjectStorageSource.cpp`) and #113956 (Parquet v3 prewhere output slots, `Reader.cpp`). The merged #110941 (renamed column) and #111693 (`ADD COLUMN` under PREWHERE) are the same family but not this trigger.

Your repro aborts verbatim for me on master `0eb5eba20b929f80c97f876870a5d2c3c5310c39` (26.8.1.1, `CMAKE_BUILD_TYPE=Debug`): `Logical error: 'Unexpected return type from greater. Expected Nullable(UInt8). Got UInt8'`, and `EXPLAIN PLAN header=1` puts the predicate inside `ReadFromObjectStorage` with `Header: id Nullable(Int64)`.

I agree it belongs here rather than in a separate issue: the predicate is type-checked against the evolved schema and evaluated against the physical file schema, which is the filter-dag-vs-parquet-schema mismatch the title names.

One addition on the workaround: `query_plan_optimize_prewhere = 0` also returns the correct rows on its own, so a regression test has to pin both prewhere settings, not just `optimize_move_to_prewhere`.

I am investigating and will follow up here with a PR or my findings.

**Comment by groeneai** [comment]
Fixed in #114521.

Root cause: `IcebergSchemaProcessor::getSchemaTransformationDag` picks the node for an existing field id from the Iceberg `type` string alone, but nullability lives in the separate `required` key, which `getFieldType` folds into ClickHouse nullability. `MODIFY COLUMN ... Nullable` flips only `required`, leaving the type string and the name unchanged, so neither the cast nor the alias branch fired and the transform forwarded the input node built from the old flag. Its output header said `Int64` while every consumer had been told `Nullable(Int64)`.

That is why only PREWHERE saw it: the fallback `FilterTransform` is built against the transform's actual header, so `greater` returned `UInt8` where the planner expected `Nullable(UInt8)`. Without the pushdown the filter sits above the reader, past the cast in `getColumnFromBlock`, so `SELECT *`, `count()` and `toTypeName()` were all correct.

The fix emits the missing cast inside the equal-type comparison, gated on the relax direction only, so the `allowPrimitiveTypeConversion` allow-list and the spec-prohibited conversions keep their current behaviour. Your point about pinning both prewhere settings is in the regression test: `optimize_move_to_prewhere=1` and `query_plan_optimize_prewhere=1` are set on every discriminating statement, because with either one off the pre-fix result is already correct.

**Comment by clickgapai** [comment]
<details>
<summary>Reproducer</summary>

```sql
# Iceberg table written by ClickHouse, then ALTER ... MODIFY COLUMN to Nullable
mkdir -p /tmp/iceberg_nullable_filter && cd /tmp/iceberg_nullable_filter

clickhouse local -q "
    SET allow_experimental_insert_into_iceberg = 1;
    CREATE TABLE t (id Int64, s String) ENGINE = IcebergLocal('lake/');
    INSERT INTO t SELECT number, toString(number) FROM numbers(5);
    ALTER TABLE t MODIFY COLUMN id Nullable(Int64);
"

clickhouse local -q "SELECT * FROM icebergLocal('lake/') WHERE id > 3"

# 26.3 / 26.5 / 26.6 / 26.7:
#   Code: 49. DB::Exception: Unexpected return type from greater.
#   Expected Nullable(UInt8). Got UInt8 ... While executing ReadFromObjectStorage. (LOGICAL_ERROR)
# master (>= a63dab1, PR #114521) and 25.8: 4  4
#
# Workaround on an affected release: SETTINGS optimize_move_to_prewhere = 0
```

</details>

**Results:**
- **Reproduces on**: `26.7, 26.6, 26.5, 26.3`
- **Does not reproduce on**: `master, 25.8`
- **Tested versions**: `master, 26.7, 26.6, 26.5, 26.3, 25.8`
- **Also tested** (unsupported, context only): `26.2` reproduces
- ✓ **Fix landed on master** in PR #114521. The releases listed above still have the bug and need the backport.

Backport PR #114521 to `26.7`, `26.6`, `26.5`, `26.3`.


CC fix PR reviewer: @SmitaRKulkarni

CC component owner: @scanhex12 @divanik

<details>
<summary>Analysis metadata</summary>

`comp-datalake` · Severity `P2` · Finding `h_issue_85029`

- Verified against `master` build `e68677ab23fa` (aarch64)
<details>
<summary>Introducing change: not identified</summary>

- The one boundary found was rejected — PR only modifies HTTP query-string parameter masking in logs; bug is in Iceberg table schema evolution and filter DAG construction, completely unrelated subsystems. — a coincidental boundary, not the cause.
- The source-build bisect converged to #95476, but it is **not** the introducer (see above) — not attributing it.

</details>



- Secondary components: `comp-formats`
- Related: #110897


</details>
