### ISSUE TITLE
Predicate push-down does not work for views

### ISSUE THREAD

**Issue by alex-zaitsev** [ClickHouse/ClickHouse#863]
ClickHouse does not push predicates, including partition column filters, down to the views. That results in very slow query performance of normal views comparing to tables.

**Comment by alexey-milovidov** [comment]
Confirmed. We have this in plans.

**Comment by tobad357** [comment]
Is there any update on this development.
As currently to get BI tools to work with AggregatingMergeTree we would need a view on top that does the sumMerge, countMerge etc from the sumState.
But it isn't workable as long as the view reads the whole table when querying

**Comment by TimonKK** [comment]
+1

**Comment by zhang2014** [comment]
What is the current state of this issue? I plan to implement it. @alexey-milovidov

**Comment by alexey-milovidov** [comment]
It is blocked by other tasks.

Direct implementation on top of existing code of `InterpreterSelectQuery` and `ExpressionAnalyzer` is possible, but most likely will introduce a huge mess (probably not - you should try).

First we want to rewrite current implementation of UNION ALL. It is not necessary for this task, but it's very important for further evolution of code.

**Comment by zhang2014** [comment]
Thank for you reply. I will try to make a pr.
BWT,   Could you please tell me more about the implementation details of the new UNION ALL?  or can you tell me about the branch that you're working on? I only found `better-union-all` and `union-all-preparation`, but they were relatively old.

**Comment by alexey-milovidov** [comment]
Basic idea is to separate InterpreterSelectQuery and InterpreterUnionQuery; and ASTSelectQuery and ASTUnionQuery. I plan to do it only after https://github.com/yandex/ClickHouse/pull/1935

**Comment by iameugenejo** [comment]
Is there any progress on this? I'm on 18.5.1 and querying against a view that has union all scans the entire rows of all tables.

**Comment by panandr** [comment]
Is there any update on this ? I see this is merged : https://github.com/yandex/ClickHouse/pull/2881/commits

This means that this is fixed now and optimized selects work for normal views ?

**Comment by moxiaofan9** [comment]
What is the current state of this issue?

**Comment by nvartolomei** [comment]
https://github.com/yandex/ClickHouse/pull/4846

**Comment by xinstein** [comment]
I am still facing this issue in 24.8.4, on a view built on top of a distributed mergetree table.


query1 succeeds instantly, while query2 runs for hours, although they are totally equivalent.

query1:
```
select *, toDateTime(data_ts, 'Asia/Shanghai')dts, toDateTime(-minus_ts/1000, 'Asia/Shanghai')mts from (SELECT
    code,
    field,
    value,
    data_ts,
    minus_ts,
    month,
    code_bucket
FROM shsz_realtime.realtime_pankou_tmp_v1_legacy
UNION ALL
SELECT
    code,
    field,
    value,
    data_ts,
    minus_ts,
    month,
    code_bucket
FROM shsz_realtime.realtime_pankou_v1
WHERE provider = 'xxxxx' )where toDate(data_ts) >= '2025-12-05' and code == '000001' and field in ('f1', 'f2') SETTINGS enable_optimize_predicate_expression=1, enable_optimize_predicate_expression_to_final_subquery=1, optimize_skip_unused_shards=1, optimize_skip_unused_shards_nesting=1, optimize_skip_merged_partitions=1
```


query2:
```
select *, toDateTime(data_ts, 'Asia/Shanghai')dts, toDateTime(-minus_ts/1000, 'Asia/Shanghai')mts from 
shsz_realtime.realtime_pankou_tmp_v1
where toDate(data_ts) >= '2025-12-05' and code == '000001' and field in ('f1', 'f2') SETTINGS enable_optimize_predicate_expression=1, enable_optimize_predicate_expression_to_final_subquery=1, optimize_skip_unused_shards=1, optimize_skip_unused_shards_nesting=1, optimize_skip_merged_partitions=1
```



Below are table schemas.




```
CREATE TABLE shsz_realtime.realtime_pankou_v1
(
    `provider` LowCardinality(String),
    `code` LowCardinality(String),
    `field` LowCardinality(String),
    `value` String,
    `data_ts` UInt64 CODEC(DoubleDelta),
    `minus_ts` Int64 DEFAULT -toUnixTimestamp64Milli(now64()),
    `month` UInt32 MATERIALIZED toUInt32(formatDateTimeInJodaSyntax(toDate(data_ts, 'Asia/Shanghai'), 'yyyyMM')),
    `code_bucket` UInt8 MATERIALIZED cityHash64(concat(code, 'bucketizer')) % 8
)
ENGINE = Distributed('default', 'shsz_realtime', 'realtime_pankou_v1_shards', cityHash64(code))
```

```
CREATE TABLE shsz_realtime.realtime_pankou_v1_shards
(
    `provider` LowCardinality(String),
    `code` LowCardinality(String),
    `field` LowCardinality(String),
    `value` String,
    `data_ts` UInt64 CODEC(DoubleDelta),
    `minus_ts` Int64,
    `month` UInt32 MATERIALIZED toUInt32(formatDateTimeInJodaSyntax(toDate(data_ts, 'Asia/Shanghai'), 'yyyyMM')),
    `code_bucket` UInt8 MATERIALIZED cityHash64(concat(code, 'bucketizer')) % 8
)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{uuid}/{shard}', '{replica}', minus_ts)
PARTITION BY (provider, month)
ORDER BY (code, data_ts, field, value)
SETTINGS index_granularity = 8192
```

```
CREATE TABLE shsz_realtime.realtime_pankou_tmp_v1_legacy
(
    `code` LowCardinality(String),
    `field` LowCardinality(String),
    `value` String,
    `data_ts` UInt64 CODEC(DoubleDelta),
    `minus_ts` Int64 DEFAULT -toUnixTimestamp64Milli(now64()),
    `month` UInt32 MATERIALIZED toUInt32(formatDateTimeInJodaSyntax(toDate(data_ts, 'Asia/Shanghai'), 'yyyyMM')),
    `code_bucket` UInt8 MATERIALIZED cityHash64(concat(code, 'bucketizer')) % 8
)
ENGINE = Distributed('default', 'shsz_realtime', 'realtime_pankou_tmp_v1_legacy_shards', cityHash64(code))
```

```
CREATE VIEW shsz_realtime.realtime_pankou_tmp_v1
(
    `code` LowCardinality(String),
    `field` LowCardinality(String),
    `value` String,
    `data_ts` UInt64,
    `minus_ts` Int64,
    `month` UInt32,
    `code_bucket` UInt8
)
AS SELECT
    code,
    field,
    value,
    data_ts,
    minus_ts,
    month,
    code_bucket
FROM shsz_realtime.realtime_pankou_tmp_v1_legacy
UNION ALL
SELECT
    code,
    field,
    value,
    data_ts,
    minus_ts,
    month,
    code_bucket
FROM shsz_realtime.realtime_pankou_v1
WHERE provider = 'xxxxx'
```

**Comment by alexey-milovidov** [comment]
@xinstein, I've created an issue: https://github.com/ClickHouse/ClickHouse/issues/91641
