### ISSUE TITLE
`test_ytsaurus_select_subset_of_columns` is flaky

### ISSUE THREAD

**Issue by Ergus** [ClickHouse/ClickHouse#88501]
Example failure from #85920 [here](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=85920&sha=392c6124eecfe5ae3b86a4c9f2f82f28ad972854&name_0=PR)  and #87994 [here](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=87994&sha=640b7026bf68b1e1aeb3615e36ad0bf6abb96493&name_0=PR):

```
File: test_ytsaurus/test_tables.py:475 - in test_ytsaurus_select_subset_of_columns
    yt = YTsaurusCLI(started_cluster, instance, YT_HOST, YT_PORT)
E   NameError: name 'YT_HOST' is not defined
```

**Comment by alexey-milovidov** [comment]
@zlobober, we will remove YTSaurus if this is not fixed.

**Comment by zlobober** [comment]
Wow, honestly don't know what it is. Let me ping relevant YTsaurus folks and see if they will be able to fix or to decide it's not needed.

**Comment by zlobober** [comment]
I was told that this logic was introduced by @MikhailBurdukov in https://github.com/ClickHouse/ClickHouse/pull/87982; let's wait for Mikhail's answer

PS I am not focusing on ClickHouse <-> YTsaurus integration any more, so in future it's better to tag PR authors for such kinds of inquiries.

**Comment by MikhailBurdukov** [comment]
Sorry, have missed the issue, I'll take a look asap

**Comment by MikhailBurdukov** [comment]
already fixed in: https://github.com/ClickHouse/ClickHouse/pull/88260
@Ergus Merging with the master should help

**Comment by MikhailBurdukov** [comment]
@alexey-milovidov If you encounter any issues with ytsaurus, please ping me directly. I try to get involved as soon as possible.

**Comment by alexey-milovidov** [comment]
@MikhailBurdukov This: https://s3.amazonaws.com/clickhouse-test-reports/json.html?REF=master&sha=cb4e1433a73ec339713f01101b8e772decdf037b&name_0=MasterCI&name_1=Integration%20tests%20%28amd_binary%2C%204%2F5%29&name_1=Integration%20tests%20%28amd_binary%2C%204%2F5%29

**Comment by MikhailBurdukov** [comment]
@alexey-milovidov FYI: https://github.com/ClickHouse/ClickHouse/pull/89096

**Comment by alexey-milovidov** [comment]
@MikhailBurdukov, it's not fixed: https://github.com/ClickHouse/ClickHouse/pull/89183

**Comment by MikhailBurdukov** [comment]
Hope it will helps: https://github.com/ClickHouse/ClickHouse/pull/89207

**Comment by al13n321** [comment]
`test_ytsaurus/test_dictionaries.py::test_yt_dictionary_id` is also flaky, idk whether the cause is the same.

Example: https://s3.amazonaws.com/clickhouse-test-reports/json.html?REF=master&sha=bf8d54cb0e4eef810376996b9de5be51a4bd05b3&name_0=MasterCI&name_1=Integration%20tests%20%28amd_binary%2C%204%2F5%29&name_1=Integration%20tests%20%28amd_binary%2C%204%2F5%29

cidb: https://play.clickhouse.com/play?user=play&run=1#V0lUSAogICAgOTAgQVMgaW50ZXJ2YWxfZGF5cwpTRUxFQ1QKICAgIHRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBBUyBkYXksCiAgICBjb3VudCgpIEFTIGZhaWx1cmVzLAogICAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlcikgQVMgcHJzLAogICAgYW55KHJlcG9ydF91cmwpIEFTIHJlcG9ydF91cmwKRlJPTSBjaGVja3MKV0hFUkUgKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZQogICAgQU5EIHRlc3RfbmFtZSBsaWtlICd0ZXN0X3l0c2F1cnVzL3Rlc3RfZGljdGlvbmFyaWVzLnB5OjolJwogICAgLS0gQU5EIGNoZWNrX25hbWUgPSAnTm9uZScKICAgIEFORCB0ZXN0X3N0YXR1cyBJTiAoJ0ZBSUwnLCAnRVJST1InKQogICAgQU5EICgoaGVhZF9yZWYgPSAnbWFzdGVyJyBBTkQgcHVsbF9yZXF1ZXN0X251bWJlciA9IDApIE9SIHB1bGxfcmVxdWVzdF9udW1iZXIgIT0gMCkKR1JPVVAgQlkgZGF5Ck9SREVSIEJZIGRheSBERVNDCg==

**Comment by alexey-milovidov** [comment]
@MikhailBurdukov, it failed: https://github.com/ClickHouse/ClickHouse/pull/89846

**Comment by MikhailBurdukov** [comment]
The fix is still unmerged 😢   https://github.com/ClickHouse/ClickHouse/pull/89207

**Comment by alexey-milovidov** [comment]
@nickitat, I merged it. If you don't like the fix, feel free to revert.

**Comment by alexey-milovidov** [comment]
@MikhailBurdukov, sorry, one more: https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=80857&sha=latest&name_0=PR

**Comment by nickitat** [comment]
It was reverted, because private tests were broken in sync pr. I will try to fix it here: https://github.com/ClickHouse/ClickHouse/pull/90168
