### ISSUE TITLE
Timeouts on `SYSTEM FLUSH LOGS` (caused by MSan overhead)

### ISSUE THREAD

**Issue by Felixoid** [ClickHouse/ClickHouse#91410]
_Important: This issue was automatically created and is used by CI to track and match failures. DO NOT edit or remove the issue title, labels, or body content._

Failure reason: DB::Exception: Timeout exceeded

Failure flags: retry_ok

Required CI action: ignore

Job pattern: Stateless tests (amd_msan%
Test pattern: %

CI report example: [Stateless tests (amd_msan, parallel)](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=91696&sha=6db1ad733e34f0d8552150d028c44dea96c97e42&name_0=PR&name_1=Stateless%20tests%20%28amd_msan%2C%20parallel%29)
Test output example:
```
2025-12-08 16:47:33 Reason: return code:  159
2025-12-08 16:47:33 [434f7079de3c] 2025.12.08 16:47:33.248684 [ 868832 ] {577c5f91-c213-41c6-9098-a9c3a573ce23} <Error> executeQuery: Code: 159. DB::Exception: Timeout exceeded (180 s) while flushing ...
2025-12-08 16:47:33 
2025-12-08 16:47:33 0. ./contrib/llvm-project/libcxx/include/__exception/exception.h:113: Poco::Exception::Exception(String const&, int) @ 0x000000005eedfe26
2025-12-08 16:47:33 1. ./ci/tmp/build/./src/Common/Exception.cpp:131: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000002b505f70
2025-12-08 16:47:33 2. DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000a89f92e
2025-12-08 16:47:33 3. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000a89e5ff
2025-12-08 16:47:33 4. DB::Exception::Exception<String, String>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<String>::type>, String&&, String&&) @ 0x000000000a89c88...
2025-12-08 16:47:33 5. ./ci/tmp/build/./src/Common/SystemLogBase.cpp:186: DB::SystemLogQueue<DB::TraceLogElement>::waitFlush(long, bool) @ 0x000000002b9bdaab
2025-12-08 16:47:33 6. ./ci/tmp/build/./src/Common/SystemLogBase.cpp:288: DB::SystemLogBase<DB::TraceLogElement>::flush(long, bool) @ 0x000000002b9bc866
2025-12-08 16:47:33 7. ./ci/tmp/build/./src/Interpreters/SystemLog.cpp:539: DB::SystemLogs::flushImpl(std::vector<std::pair<String, String>, std::allocator<std::pair<String, String>>> const&, bool, bo...
2025-12-08 16:47:33 8. ./ci/tmp/build/./src/Interpreters/SystemLog.cpp:556: DB::SystemLogs::flush(std::vector<std::pair<String, String>, std::allocator<std::pair<String, String>>> const&) @ 0x00000000...
2025-12-08 16:47:33 9. ./ci/tmp/build/./src/Interpreters/InterpreterSystemQuery.cpp:860: DB::InterpreterSystemQuery::execute() @ 0x00000000431b455e
2025-12-08 16:47:33 10. ./ci/tmp/build/./src/Interpreters/executeQuery.cpp:1746: DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::...
2025-12-08 16:47:33 11. ./ci/tmp/build/./src/Interpreters/executeQuery.cpp:1967: DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x00000...
2025-12-08 16:47:33 12. ./ci/tmp/build/./src/Server/TCPHandler.cpp:777: DB::TCPHandler::runImpl() @ 0x0000000051ab164d
2025-12-08 16:47:33 13. ./ci/tmp/build/./src/Server/TCPHandler.cpp:2873: DB::TCPHandler::run() @ 0x0000000051b25e0e
2025-12-08 16:47:33 14. ./ci/tmp/build/./base/poco/Net/src/TCPServerConnection.cpp:40: Poco::Net::TCPServerConnection::start() @ 0x000000005f178960
2025-12-08 16:47:33 15. ./ci/tmp/build/./base/poco/Net/src/TCPServerDispatcher.cpp:115: Poco::Net::TCPServerDispatcher::run() @ 0x000000005f179952
2025-12-08 16:47:33 16. ./ci/tmp/build/./base/poco/Foundation/src/ThreadPool.cpp:205: Poco::PooledThread::run() @ 0x000000005f0207f5
2025-12-08 16:47:33 17. ./ci/tmp/build/./base/poco/Foundation/src/Thread.cpp:45: Poco::(anonymous namespace)::RunnableHolder::run() @ 0x000000005f01ccae
2025-12-08 16:47:33 18. ./base/poco/Foundation/src/Thread_POSIX.cpp:341: Poco::ThreadImpl::runnableEntry(void*) @ 0x000000005f019711
2025-12-08 16:47:33 19. ? @ 0x0000000000094ac3
2025-12-08 16:47:33 20. ? @ 0x00000000001268c0
2025-12-08 16:47:33 
2025-12-08 16:47:33 Received exception from server (version 25.12.1):
2025-12-08 16:47:33 Code: 159. DB::Exception: Received from localhost:9000. DB::Exception: Timeout exceeded (180 s) while flushing system log 'DB::SystemLogQueue<DB::TraceLogElement>'.. (TIMEOUT_EXCEE...
2025-12-08 16:47:33 (query: SYSTEM FLUSH LOGS /* all tables */;)
2025-12-08 16:47:33 , result:
2025-12-08 16:47:33 
2025-12-08 16:47:33 
2025-12-08 16:47:33 
2025-12-08 16:47:33 stdout:
2025-12-08 16:47:33 
2025-12-08 16:47:33 
2025-12-08 16:47:33 Settings used in the test: --max_insert_threads 2 --group_by_two_level_threshold 1000000 --group_by_two_level_threshold_bytes 33658432 --distributed_aggregation_memory_efficient 1 ...
2025-12-08 16:47:33 
2025-12-08 16:47:33 MergeTree settings used in test: --ratio_of_defaults_for_sparse_serialization 0.0 --prefer_fetch_merged_part_size_threshold 1 --vertical_merge_algorithm_min_rows_to_activate 1 --ve...
2025-12-08 16:47:33 
2025-12-08 16:47:33 Database: test_naoxh389
```

**Comment by maxknv** [comment]
Retry feature retries failed tests after the main run just to mark them "retry_ok" or "retry_fail". It should not be the reason for these errors

**Comment by maxknv** [comment]
it might be a log cluster issue

**Comment by Felixoid** [comment]
Can't really say. It's very suspicious that it affects only MSAN tests.

Although, there's another [report](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=90677&sha=f8f95f152b873a03c694e3b1e73302dd0f3823a1&name_0=PR&name_1=Stateless%20tests%20%28amd_msan%2C%20parallel%29&name_1=Stateless%20tests%20%28amd_msan%2C%20parallel%29) before your PR is merged

Here's more detailed aggregation of the same [query](https://play.clickhouse.com/play?user=play&run=1#V0lUSAogICAgOTAgQVMgaW50ZXJ2YWxfZGF5cwpTRUxFQ1QKICAgIHRvU3RhcnRPZkhvdXIoY2hlY2tfc3RhcnRfdGltZSkgQVMgZGF5LAogICAgY291bnREaXN0aW5jdChjb21taXRfc2hhKSBBUyBmYWlsdXJlcywKICAgIGdyb3VwVW5pcUFycmF5KGNoZWNrX25hbWUpIEFTIGNoZWNrX25hbWVzLAogICAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlcikgQVMgcHJzLAogICAgZ3JvdXBVbmlxQXJyYXkocmVwb3J0X3VybCkgQVMgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSAoY2hlY2tfc3RhcnRfdGltZSBCRVRXRUVOICcyMDI1LTExLTE1JyBBTkQgJzIwMjUtMTEtMjYnKQogICAgQU5EIHRlc3RfY29udGV4dF9yYXcgTElLRSAnJVRpbWVvdXQgZXhjZWVkZWQgKDE4MCBzKSB3aGlsZSBmbHVzaGluZyBzeXN0ZW0gbG9nJScKICAgIC0tIEFORCBjaGVja19uYW1lID0gJ1N0YXRlbGVzcyB0ZXN0cyAoYW1kX21zYW4sIHBhcmFsbGVsKScKICAgIEFORCB0ZXN0X3N0YXR1cyBJTiAoJ0ZBSUwnLCAnRVJST1InKQogICAgQU5EICgoaGVhZF9yZWYgPSAnbWFzdGVyJyBBTkQgcHVsbF9yZXF1ZXN0X251bWJlciA9IDApIE9SIHB1bGxfcmVxdWVzdF9udW1iZXIgIT0gMCkKR1JPVVAgQlkgZGF5Ck9SREVSIEJZIGRheSBERVNDCg==)

**Comment by maxknv** [comment]
> Although, there's another [report](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=90677&sha=f8f95f152b873a03c694e3b1e73302dd0f3823a1&name_0=PR&name_1=Stateless%20tests%20%28amd_msan%2C%20parallel%29&name_1=Stateless%20tests%20%28amd_msan%2C%20parallel%29) before your PR is merged

this run includes my change, actually, (you can see `Retries` stage in the job report), so timing is perfectly aligned

**Comment by antaljanosbenjamin** [comment]
I have merged the PR #89408 on Nov 17th. It might be connected, but I am not sure.

**Comment by azat** [comment]
Refs: https://github.com/ClickHouse/ClickHouse/issues/57984

**Comment by Algunenano** [comment]
Seeing #91472 I see that the time to prepare the data (from LogElement to block) scales pretty bad with size in msan build. 

Reviewing recent improvements in https://github.com/ClickHouse/ClickHouse/pull/85159/ I suspect we can make it better by avoiding using Fields when inserting in the many Array(LowCardinality(String)) columns.

I'll try adding it in  #91472 to see what happens

**Comment by azat** [comment]
I've looked at the new timings that has been added in #91472, and the biggest problem AFAICS is with `trace_log` - https://pastila.nl/?00d9bf57/4aaf65fac3c2a4e43f55cd58d91cf8f4#5WT6b0svzQH8IMyaHDD9HA==

I've looked at perf and I see two problems
- demangling is very slow - approx 50% of time - https://pastila.nl/?001ddeba/c8033cb5b5e5565887965f8df08cc280#a0hBne8axAezL0edReSg1A== - I've verified this and w/o demangle it is indeed 50% faster (12k entries, slow 5.6sec - likely address cache, hot w/ demangle 3.6sec, w/o 1.8-1.4 sec)
  - simply `__attribute__((no_sanitize("memory")))` will not help, since we need to apply it for inner functions, I will try to do this via blacklist - https://github.com/ClickHouse/ClickHouse/pull/91579
- And second problem is insert into array - https://pastila.nl/?002c0024/690ba17c650494481509695a5d51e488#gxFYHa6ezORT8fkKQs5THw== - #91472 should help

P.S. history of `system flush logs` failures - https://pastila.nl/?001c4021/3355775f0dc01f03432e4693bac81813#allc1meXfknHEl+4eDOOaA==

_P.P.S. don't forget to zoom out until the pastila will fit into line_

**Comment by azat** [comment]
Nope, still a problem for flushing query_log under MSan - https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=92390&sha=latest&name_0=PR&name_1=Stateless+tests+%28amd_msan%2C+parallel%29

**Comment by Algunenano** [comment]
AFAICT now we spent most of the time processing settings, and the more settings we change and randomize the slower convering it to blocks becomes. I've done a few experiments in https://github.com/ClickHouse/ClickHouse/pull/92716, let's see how it goes

**Comment by Algunenano** [comment]
https://github.com/ClickHouse/ClickHouse/pull/92716
