### ISSUE TITLE
Remote JDBC bridge connection issue (timeout)

### ISSUE THREAD

**Issue by sergey-buturlakin** [ClickHouse/ClickHouse#9609]
**Describe the bug or unexpected behaviour**
Trying to access JDBC bridge deployed on a remote host almost always produces the following error:

```Code: 410, e.displayText() = DB::Exception: jdbc-bridge is not running. Please, start it manually```

Could be related to #8723

**The reason**
Communication with JDBC bridge is implemented using ```ReadWriteBufferFromHTTP``` class without providing HTTP timeouts from configuration, e.g.:

```ReadWriteBufferFromHTTP buf(uri, Poco::Net::HTTPRequest::HTTP_POST, nullptr);```

In such case class'es constructor automatically provides default value for timeouts parameter with all values equal to zero and these values are passed to Poco HTTPSession, replacing Poco's default values.
This leads to ```TimeoutException``` in ```SocketImpl::connect``` method:

```
  if (!poll(timeout, SELECT_READ | SELECT_WRITE | SELECT_ERROR))
    throw Poco::TimeoutException("connect timed out", address.toString());
```

**The proposition**
Provide timeouts to all JDBC bridge related usages.

XDBCBridgeHelper.h - getIdentifierQuotingStyle
```
ReadWriteBufferFromHTTP buf(uri, Poco::Net::HTTPRequest::HTTP_POST, nullptr, ConnectionTimeouts::getHTTPTimeouts(context));
```

XDBCBridgeHelper.h - checkBridgeIsRunning
```
ReadWriteBufferFromHTTP buf(ping_url, Poco::Net::HTTPRequest::HTTP_GET, nullptr, ConnectionTimeouts::getHTTPTimeouts(context));
```

ITableFunctionXDBC.cpp - ITableFunctionXDBC::executeImpl
```
ReadWriteBufferFromHTTP buf(columns_info_uri, Poco::Net::HTTPRequest::HTTP_POST, nullptr, ConnectionTimeouts::getHTTPTimeouts(context));
```

**Nice to have**
Exception logging in XDBCBridgeHelper.h - checkBridgeIsRunning
```
        try
        {
            ReadWriteBufferFromHTTP buf(ping_url, Poco::Net::HTTPRequest::HTTP_GET, nullptr);
            return checkString(XDBCBridgeHelper::PING_OK_ANSWER, buf);
        }
        catch (...)
        {
---> logging here could save a lot of time in some cases
            return false;
        }
```

**Comment by zhicwu** [comment]
Thank you @sergey-buturlakin. I can confirm your solution works very well - tested using 50 concurrent users and no more timeout :) Would be great if someone can create a pull request to fix this in trunk.

**Comment by filimonov** [comment]
@sergey-buturlakin why don't you send a PR?

**Comment by WesleyBatista** [comment]
So well detailed but no implementation :cry: 

Anyone with a workaround for this? 

Still happening on ClickHouse version 20.5.4, using the [bridge](https://github.com/ClickHouse/clickhouse-jdbc-bridge) to postgres datasource:
```
Received exception from server (version 20.5.4):
Code: 410. DB::Exception: Received from <host>:9000. DB::Exception: jdbc-bridge is not running. Please, start it manually. 

0 rows in set. Elapsed: 0.102 sec. 
```

**Comment by WesleyBatista** [comment]
Today I stumbled upon this other issue https://github.com/ClickHouse/clickhouse-jdbc-bridge/issues/47, and it also worked for me when I specified the ` --listen-host 0.0.0.0`.

I suspect it is something on my `/etc/hosts` file... Anyway, it's working now :tada:

**Comment by alexey-milovidov** [comment]
Looks like it's fixed in https://github.com/ClickHouse/ClickHouse/pull/11690.

**Comment by zhicwu** [comment]
OK, I performed stress test(20 concurrent users) against official docker image `yandex/clickhouse-server:20.8`(keep_alive_timeout=300) and JDBC bridge 2.0.

Query| # Samples | Average | Median | 90% Line | 95% Line | 99% Line | Min | Max | Error % | Throughput
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
select * from jdbc('mariadb', 'select 1') | 200,000 | 186 | 116 | 190 | 1,050 | 1,750 | 24 | 3,110 | 0.051375 | 107.2074

Most of the errors are `jdbc-bridge is not running`, while the rest(~6%) is timeout like below. No exception observed on JDBC bridge side. I also performed similar stress test by sending http requests to JDBC bridge directly and it works fine without any issue.
```bash
268198- (version 20.8.9.6 (official build))
268235:2020.12.12 03:31:33.460806 [ 114 ] {0a3d0e0b-16ac-4b8a-a534-106ff76b533e} <Error> executeQuery: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Timeout: connect timed out: 10.0.8.9:9019 (version 20.8.9.6 (official build)) (from 10.0.0.4:63671) (in query: select * from jdbc('mariadb', 'constant') FORMAT TabSeparatedWithNamesAndTypes ), Stack trace (when copying this message, always include the lines below):
268658-
268659-0. Poco::TimeoutException::TimeoutException(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x18b6b48f in /usr/bin/clickhouse
268932-1. ? @ 0x18a7fdd5 in /usr/bin/clickhouse
268973-2. Poco::Net::HTTPSession::connect(Poco::Net::SocketAddress const&) @ 0x18a49cb5 in /usr/bin/clickhouse
269077-3. Poco::Net::HTTPClientSession::reconnect() @ 0x18a36bb8 in /usr/bin/clickhouse
269158-4. Poco::Net::HTTPClientSession::sendRequest(Poco::Net::HTTPRequest&) @ 0x18a37f18 in /usr/bin/clickhouse
269264-5. DB::detail::ReadWriteBufferFromHTTPBase<std::__1::shared_ptr<DB::UpdatableSession> >::call(Poco::URI, Poco::Net::HTTPResponse&) @ 0x12bc5f75 in /usr/bin/clickhouse
269431-6. DB::detail::ReadWriteBufferFromHTTPBase<std::__1::shared_ptr<DB::UpdatableSession> >::ReadWriteBufferFromHTTPBase(std::__1::shared_ptr<DB::UpdatableSession>, Poco::URI, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<void (std::__1::basic_ostream<char, std::__1::char_traits<char> >&)>, Poco::Net::HTTPBasicCredentials const&, unsigned long, std::__1::vector<std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >, DB::RemoteHostFilter const&) @ 0x12bc649b in /usr/bin/clickhouse
270331-7. DB::ReadWriteBufferFromHTTP::ReadWriteBufferFromHTTP(Poco::URI, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<void (std::__1::basic_ostream<char, std::__1::char_traits<char> >&)>, DB::ConnectionTimeouts const&, unsigned long, Poco::Net::HTTPBasicCredentials const&, unsigned long, std::__1::vector<std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > const&, DB::RemoteHostFilter const&) @ 0x12bc6e96 in /usr/bin/clickhouse
271179-8. DB::ITableFunctionXDBC::executeImpl(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0x14fcd643 in /usr/bin/clickhouse
271413-9. DB::ITableFunction::execute(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0x155dfce1 in /usr/bin/clickhouse
271639-10. DB::Context::executeTableFunction(std::__1::shared_ptr<DB::IAST> const&) @ 0x155aaf3e in /usr/bin/clickhouse
271752-11. DB::JoinedTables::getLeftTableStorage() @ 0x15a5d224 in /usr/bin/clickhouse
271832-12. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&) @ 0x15895d3b in /usr/bin/clickhouse
272424-13. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x15896f09 in /usr/bin/clickhouse
272827-14. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x15a10ab7 in /usr/bin/clickhouse
273248-15. DB::InterpreterFactory::get(std::__1::shared_ptr<DB::IAST>&, DB::Context&, DB::QueryProcessingStage::Enum) @ 0x157f6adf in /usr/bin/clickhouse
273395-16. ? @ 0x15b98b88 in /usr/bin/clickhouse
273437-17. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, DB::Context&, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>) @ 0x15b9aa99 in /usr/bin/clickhouse
273952-18. DB::HTTPHandler::processQuery(DB::Context&, Poco::Net::HTTPServerRequest&, HTMLForm&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&) @ 0x161d9979 in /usr/bin/clickhouse
274136-19. DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&) @ 0x161dd42b in /usr/bin/clickhouse
274270-20. Poco::Net::HTTPServerConnection::run() @ 0x18a46af3 in /usr/bin/clickhouse
274349-21. Poco::Net::TCPServerConnection::start() @ 0x18a84d0b in /usr/bin/clickhouse
274429-22. Poco::Net::TCPServerDispatcher::run() @ 0x18a85428 in /usr/bin/clickhouse
274507-23. Poco::PooledThread::run() @ 0x18c03b26 in /usr/bin/clickhouse
274573-24. Poco::ThreadImpl::runnableEntry(void*) @ 0x18bfef20 in /usr/bin/clickhouse
274652-25. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
274726-26. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
```

**Comment by zhicwu** [comment]
So I commented [this line](https://github.com/ClickHouse/ClickHouse/blob/v20.8.9.6-lts/src/Common/XDBCBridgeHelper.h#L177) and got slightly improved results(error rate dropped to ~0.3% from 5%). I can still see timeout error and a few errors saying `clickhouse-jdbc-bridge is not responding`.

Query | # Samples | Average | Median | 90% Line | 95% Line | 99% Line | Min | Max | Error % | Throughput
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
select * from jdbc('mariadb', 'select 1') | 200000 | 154 | 73 | 101 | 114 | 164 | 13 | 42514 | 0.343% | 128.901


JDBC/ODBC bridge could be a remote process, so I believe `startBridge` won't help in that case. Moreover, `checkBridgeIsRunning` might not be helpful, especially when multiple threads calling the same method. I'll change `checkBridgeIsRunning` method by always return true and try again later.

**Comment by zhicwu** [comment]
Below are logs collected from both client and server(`checkBridgeIsRunning()` is changed to always return true, so no called made to `/ping` in strace log).

* Client
```bash
curl -v -u 'default:' "http://ch.local.domain:8123/?query=select%20%2A%20from%20jdbc%28%27mariad
b%27%2C%27constant%27%29"
*   Trying *.*.*.*:8123...
* TCP_NODELAY set
* Connected to ch.local.domain (*.*.*.*) port 8123 (#0)
* Server auth using Basic with user 'default'
> GET /?query=select%20%2A%20from%20jdbc%28%27mariadb%27%2C%27constant%27%29 HTTP/1.1
> Host: ch.local.domain:8123
> Authorization: Basic ZGVmYXVsdDo=
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Mon, 14 Dec 2020 04:43:18 GMT
< Connection: Keep-Alive
< Content-Type: text/tab-separated-values; charset=UTF-8
< X-ClickHouse-Server-Display-Name: ch-server
< Transfer-Encoding: chunked
< X-ClickHouse-Query-Id: 63559934-ea73-4216-93ce-60e58953180f
< X-ClickHouse-Format: TabSeparated
< X-ClickHouse-Timezone: UTC
< Keep-Alive: timeout=300
< X-ClickHouse-Summary: {"read_rows":"0","read_bytes":"0","written_rows":"0","written_bytes":"0","total_rows_to_read":"0"}
<
1
* Connection #0 to host ch.local.domain left intact
```

* Server
```bash
strace -e trace=network -fp <pid>
...
[pid  2754] accept(20, {sa_family=AF_INET, sin_port=htons(1958), sin_addr=inet_addr("10.0.0.4")}, [128->16]) = 28
[pid  2754] getsockname(28, {sa_family=AF_INET, sin_port=htons(8123), sin_addr=inet_addr("10.0.0.141")}, [128->16]) = 0
[pid  2754] setsockopt(28, SOL_TCP, TCP_NODELAY, [1], 4) = 0
[pid  9625] setsockopt(28, SOL_SOCKET, SO_RCVTIMEO, "\10\7\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 16) = 0
[pid  9625] recvfrom(28, "GET /?query=select%20%2A%20from%"..., 4096, 0, NULL, NULL) = 188
[pid  9625] getpeername(28, {sa_family=AF_INET, sin_port=htons(1958), sin_addr=inet_addr("10.0.0.4")}, [128->16]) = 0
[pid  9625] getsockname(28, {sa_family=AF_INET, sin_port=htons(8123), sin_addr=inet_addr("10.0.0.141")}, [128->16]) = 0
[pid  9625] socket(AF_INET, SOCK_STREAM, IPPROTO_IP) = 31
[pid  9625] connect(31, {sa_family=AF_INET, sin_port=htons(9019), sin_addr=inet_addr("10.0.14.3")}, 16) = -1 EINPROGRESS (Operation now in progress)
[pid  9625] getsockopt(31, SOL_SOCKET, SO_ERROR, [0], [4]) = 0
[pid  9625] setsockopt(31, SOL_SOCKET, SO_RCVTIMEO, "\10\7\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 16) = 0
[pid  9625] setsockopt(31, SOL_SOCKET, SO_SNDTIMEO, "\10\7\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 16) = 0
[pid  9625] setsockopt(31, SOL_TCP, TCP_NODELAY, [1], 4) = 0
[pid  9625] sendto(31, "POST /columns_info?connection_st"..., 150, 0, NULL, 0) = 150
[pid  9625] shutdown(31, SHUT_WR)       = 0
[pid  9625] recvfrom(31, "HTTP/1.1 200 OK\r\nconnection: clo"..., 4096, 0, NULL, NULL) = 106
[pid  9625] socket(AF_INET, SOCK_STREAM, IPPROTO_IP) = 31
[pid  9625] connect(31, {sa_family=AF_INET, sin_port=htons(9019), sin_addr=inet_addr("10.0.14.3")}, 16) = -1 EINPROGRESS (Operation now in progress)
[pid  9625] getsockopt(31, SOL_SOCKET, SO_ERROR, [0], [4]) = 0
[pid  9625] setsockopt(31, SOL_SOCKET, SO_RCVTIMEO, "\10\7\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 16) = 0
[pid  9625] setsockopt(31, SOL_SOCKET, SO_SNDTIMEO, "\10\7\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 16) = 0
[pid  9625] setsockopt(31, SOL_TCP, TCP_NODELAY, [1], 4) = 0
[pid  9625] sendto(31, "POST /identifier_quote?connectio"..., 99, 0, NULL, 0) = 99
[pid  9625] shutdown(31, SHUT_WR)       = 0
[pid  9625] recvfrom(31, "HTTP/1.1 200 OK\r\nconnection: clo"..., 4096, 0, NULL, NULL) = 59
[pid  9625] socket(AF_INET, SOCK_STREAM, IPPROTO_IP) = 31
[pid  9625] connect(31, {sa_family=AF_INET, sin_port=htons(9019), sin_addr=inet_addr("10.0.14.3")}, 16) = -1 EINPROGRESS (Operation now in progress)
[pid  9625] getsockopt(31, SOL_SOCKET, SO_ERROR, [0], [4]) = 0
[pid  9625] setsockopt(31, SOL_SOCKET, SO_RCVTIMEO, "\10\7\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 16) = 0
[pid  9625] setsockopt(31, SOL_SOCKET, SO_SNDTIMEO, "\10\7\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 16) = 0
[pid  9625] setsockopt(31, SOL_TCP, TCP_NODELAY, [1], 4) = 0
[pid  9625] sendto(31, "POST /?connection_string=mariadb"..., 212, 0, NULL, 0) = 212
[pid  9625] sendto(31, "20\r\nquery=SELECT `1` FROM `const"..., 38, 0, NULL, 0) = 38
[pid  9625] sendto(31, "0\r\n\r\n", 5, 0, NULL, 0) = 5
[pid  9625] recvfrom(31, "HTTP/1.1 200 OK\r\ntransfer-encodi"..., 4096, 0, NULL, NULL) = 77
[pid  9625] sendto(28, "HTTP/1.1 200 OK\r\nDate: Mon, 14 D"..., 478, 0, NULL, 0) = 478
[pid  9625] sendto(28, "\r\n", 2, 0, NULL, 0) = 2
[pid  9625] sendto(28, "2\r\n1\n\r\n", 7, 0, NULL, 0) = 7
[pid  9625] sendto(28, "0\r\n\r\n", 5, 0, NULL, 0) = 5
[pid  9625] recvfrom(28, "", 4096, 0, NULL, NULL) = 0
...
```

**Comment by alexey-milovidov** [comment]
So, the timeout is set to `\10\7\0\0\0\0\0\0\0\0\0\0\0\0\0\0` (in struct timeval).

```
\10\7\0\0\0\0\0\0\0\0\0\0\0\0\0\0
 ^  ^ ^ ^ ^ ^ ^ ^
```

This is the number of seconds in little endian with octal escaping: 8 + 7 * 256 = 1800 seconds.
It looks enough.

Maybe connection timeout is too low?

**Comment by traceon** [comment]
@alexey-milovidov Can `jdbc-bridge is not running`-type errors be similar to one that was fixed in #18278 for `odbc-bridge`?

**Comment by alexey-milovidov** [comment]
We have finally found the culprit. The fix is on the way.

**Comment by alexey-milovidov** [comment]
https://github.com/ClickHouse/ClickHouse/pull/23771

**Comment by zhicwu** [comment]
I believe v21.6.5.37 contains the fix, but unfortunately we still have the same issue:

* time out
``` text
2021.06.23 07:09:42.470883 [ 338 ] {} <Trace> DynamicQueryHandler: Request URI: /?extremes=0&max_execution_time=30&compress=1&query_id=cd5b1f32-7edc-4d9c-86c0-0c947e35cb05&database=system
2021.06.23 07:09:42.471637 [ 338 ] {cd5b1f32-7edc-4d9c-86c0-0c947e35cb05} <Debug> executeQuery: (from x.x.x.x:12125, using production parser) select * from jdbc('mariadb', '1 UInt8', 'select 1') FORMAT TabSeparatedWithNamesAndTypes;
2021.06.23 07:09:42.471806 [ 338 ] {cd5b1f32-7edc-4d9c-86c0-0c947e35cb05} <Trace> ContextAccess (default): Access granted: CREATE TEMPORARY TABLE, JDBC ON *.*
2021.06.23 07:09:42.473383 [ 338 ] {cd5b1f32-7edc-4d9c-86c0-0c947e35cb05} <Trace> ReadWriteBufferFromHTTP: Sending request to http://jdbc-bridge:9019/ping
2021.06.23 07:09:43.479958 [ 338 ] {cd5b1f32-7edc-4d9c-86c0-0c947e35cb05} <Trace> ReadWriteBufferFromHTTP: Sending request to http://jdbc-bridge:9019/columns_info?connection_string=mariadb&schema=1%20UInt8&table=select%201&external_table_functions_use_nulls=true
2021.06.23 07:09:44.482671 [ 338 ] {cd5b1f32-7edc-4d9c-86c0-0c947e35cb05} <Error> executeQuery: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Timeout: connect timed out: y.y.y.y:9019 (version 21.6.5.37 (official build)) (from x.x.x.x:12125) (in query: select * from jdbc('mariadb', '1 UInt8', 'select 1') FORMAT TabSeparatedWithNamesAndTypes;), Stack trace (when copying this message, always include the lines below):

0. Poco::Net::SocketImpl::connect(Poco::Net::SocketAddress const&, Poco::Timespan const&) @ 0x12a38f1b in /usr/bin/clickhouse
1. Poco::Net::HTTPSession::connect(Poco::Net::SocketAddress const&) @ 0x12a179b6 in /usr/bin/clickhouse
2. Poco::Net::HTTPClientSession::reconnect() @ 0x12a066cf in /usr/bin/clickhouse
3. Poco::Net::HTTPClientSession::sendRequest(Poco::Net::HTTPRequest&) @ 0x12a0540c in /usr/bin/clickhouse
4. DB::detail::ReadWriteBufferFromHTTPBase<std::__1::shared_ptr<DB::UpdatableSession> >::call(Poco::URI, Poco::Net::HTTPResponse&) @ 0xdacba79 in /usr/bin/clickhouse
5. DB::detail::ReadWriteBufferFromHTTPBase<std::__1::shared_ptr<DB::UpdatableSession> >::ReadWriteBufferFromHTTPBase(std::__1::shared_ptr<DB::UpdatableSession>, Poco::URI, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<void (std::__1::basic_ostream<char, std::__1::char_traits<char> >&)>, Poco::Net::HTTPBasicCredentials const&, unsigned long, std::__1::vector<std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >, DB::RemoteHostFilter const&) @ 0xdac8162 in /usr/bin/clickhouse
6. DB::ReadWriteBufferFromHTTP::ReadWriteBufferFromHTTP(Poco::URI, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<void (std::__1::basic_ostream<char, std::__1::char_traits<char> >&)>, DB::ConnectionTimeouts const&, unsigned long, Poco::Net::HTTPBasicCredentials const&, unsigned long, std::__1::vector<std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > const&, DB::RemoteHostFilter const&) @ 0xdac7937 in /usr/bin/clickhouse
7. DB::ITableFunctionXDBC::getActualTableStructure(std::__1::shared_ptr<DB::Context>) const @ 0xee799f3 in /usr/bin/clickhouse
8. DB::ITableFunctionXDBC::executeImpl(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::ColumnsDescription) const @ 0xee7a0df in /usr/bin/clickhouse
9. DB::ITableFunction::execute(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::ColumnsDescription) const @ 0xf44b9c3 in /usr/bin/clickhouse
10. DB::Context::executeTableFunction(std::__1::shared_ptr<DB::IAST> const&) @ 0xf51f7bb in /usr/bin/clickhouse
11. DB::JoinedTables::getLeftTableStorage() @ 0xfa870af in /usr/bin/clickhouse
12. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&) @ 0xf8d3e59 in /usr/bin/clickhouse
13. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0xf8d351e in /usr/bin/clickhouse
14. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0xfa4c027 in /usr/bin/clickhouse
15. ? @ 0xf6c0231 in /usr/bin/clickhouse
16. DB::InterpreterFactory::get(std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&) @ 0xf6bf8a2 in /usr/bin/clickhouse
17. ? @ 0xfc0a204 in /usr/bin/clickhouse
18. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>) @ 0xfc0dfd5 in /usr/bin/clickhouse
19. DB::HTTPHandler::processQuery(std::__1::shared_ptr<DB::Context>, DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&) @ 0x103c36bf in /usr/bin/clickhouse
20. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x103c6e49 in /usr/bin/clickhouse
21. DB::HTTPServerConnection::run() @ 0x1044acd0 in /usr/bin/clickhouse
22. Poco::Net::TCPServerConnection::start() @ 0x12a3fd4f in /usr/bin/clickhouse
23. Poco::Net::TCPServerDispatcher::run() @ 0x12a417da in /usr/bin/clickhouse
24. Poco::PooledThread::run() @ 0x12b7ab39 in /usr/bin/clickhouse
25. Poco::ThreadImpl::runnableEntry(void*) @ 0x12b76b2a in /usr/bin/clickhouse
26. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
27. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so

2021.06.23 07:09:44.483109 [ 338 ] {cd5b1f32-7edc-4d9c-86c0-0c947e35cb05} <Error> DynamicQueryHandler: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Timeout: connect timed out: y.y.y.y:9019, Stack trace (when copying this message, always include the lines below):
...
2021.06.23 07:09:44.483730 [ 338 ] {cd5b1f32-7edc-4d9c-86c0-0c947e35cb05} <Debug> MemoryTracker: Peak memory usage (for query): 0.00 B.
```

* jdbc-bridge not running
``` text
2021.06.23 07:09:43.480826 [ 332 ] {} <Trace> DynamicQueryHandler: Request URI: /?extremes=0&max_execution_time=30&compress=1&query_id=4539c134-fe7a-487d-849b-02db5657aced&database=system
2021.06.23 07:09:43.481401 [ 332 ] {4539c134-fe7a-487d-849b-02db5657aced} <Debug> executeQuery: (from x.x.x.x:12146, using production parser) select * from jdbc('mariadb', '1 UInt8', 'select 1') FORMAT TabSeparatedWithNamesAndTypes;
2021.06.23 07:09:43.481559 [ 332 ] {4539c134-fe7a-487d-849b-02db5657aced} <Trace> ContextAccess (default): Access granted: CREATE TEMPORARY TABLE, JDBC ON *.*
2021.06.23 07:09:43.481667 [ 332 ] {4539c134-fe7a-487d-849b-02db5657aced} <Trace> ReadWriteBufferFromHTTP: Sending request to http://jdbc-bridge:9019/ping
2021.06.23 07:09:44.482156 [ 332 ] {4539c134-fe7a-487d-849b-02db5657aced} <Trace> JDBCBridgeHelper: clickhouse-jdbc-bridge is not running, will try to start it
2021.06.23 07:09:44.482909 [ 332 ] {4539c134-fe7a-487d-849b-02db5657aced} <Error> executeQuery: Code: 410, e.displayText() = DB::Exception: clickhouse-jdbc-bridge is not running. Please, start it manually (version 21.6.5.37 (official build)) (from x.x.x.x:12146) (in query: select * from jdbc('mariadb', '1 UInt8', 'select 1') FORMAT TabSeparatedWithNamesAndTypes;), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x8b6cbba in /usr/bin/clickhouse
1. DB::IBridgeHelper::startBridgeCommand() const @ 0x10384cd0 in /usr/bin/clickhouse
2. DB::IBridgeHelper::startBridgeSync() const @ 0x10382990 in /usr/bin/clickhouse
3. DB::ITableFunctionXDBC::startBridgeIfNot(std::__1::shared_ptr<DB::Context>) const @ 0xee79624 in /usr/bin/clickhouse
4. DB::ITableFunctionXDBC::executeImpl(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::ColumnsDescription) const @ 0xee7a0b9 in /usr/bin/clickhouse
5. DB::ITableFunction::execute(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::ColumnsDescription) const @ 0xf44b9c3 in /usr/bin/clickhouse
6. DB::Context::executeTableFunction(std::__1::shared_ptr<DB::IAST> const&) @ 0xf51f7bb in /usr/bin/clickhouse
7. DB::JoinedTables::getLeftTableStorage() @ 0xfa870af in /usr/bin/clickhouse
8. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&) @ 0xf8d3e59 in /usr/bin/clickhouse
9. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0xf8d351e in /usr/bin/clickhouse
10. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0xfa4c027 in /usr/bin/clickhouse
11. ? @ 0xf6c0231 in /usr/bin/clickhouse
12. DB::InterpreterFactory::get(std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&) @ 0xf6bf8a2 in /usr/bin/clickhouse
13. ? @ 0xfc0a204 in /usr/bin/clickhouse
14. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>) @ 0xfc0dfd5 in /usr/bin/clickhouse
15. DB::HTTPHandler::processQuery(std::__1::shared_ptr<DB::Context>, DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&) @ 0x103c36bf in /usr/bin/clickhouse
16. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x103c6e49 in /usr/bin/clickhouse
17. DB::HTTPServerConnection::run() @ 0x1044acd0 in /usr/bin/clickhouse
18. Poco::Net::TCPServerConnection::start() @ 0x12a3fd4f in /usr/bin/clickhouse
19. Poco::Net::TCPServerDispatcher::run() @ 0x12a417da in /usr/bin/clickhouse
20. Poco::PooledThread::run() @ 0x12b7ab39 in /usr/bin/clickhouse
21. Poco::ThreadImpl::runnableEntry(void*) @ 0x12b76b2a in /usr/bin/clickhouse
22. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
23. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so

2021.06.23 07:09:44.483391 [ 332 ] {4539c134-fe7a-487d-849b-02db5657aced} <Error> DynamicQueryHandler: Code: 410, e.displayText() = DB::Exception: clickhouse-jdbc-bridge is not running. Please, start it manually, Stack trace (when copying this message, always include the lines below):
...
2021.06.23 07:09:44.484015 [ 332 ] {4539c134-fe7a-487d-849b-02db5657aced} <Debug> MemoryTracker: Peak memory usage (for query): 0.00 B.
```
